"""initial MVP schema

Revision ID: f4531d925d39
Revises: 
Create Date: 2026-10-08 21:01:29.112670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4531d925d39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('division', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('module_path', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_definitions_division'), 'agent_definitions', ['division'], unique=False)
    op.create_index(op.f('ix_agent_definitions_key'), 'agent_definitions', ['key'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('genes', sa.String(length=128), nullable=False),
    sa.Column('uniprot', sa.String(length=128), nullable=False),
    sa.Column('organ', sa.String(length=256), nullable=False),
    sa.Column('inheritance', sa.String(length=128), nullable=False),
    sa.Column('omim', sa.String(length=256), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('soc', sa.Text(), nullable=False),
    sa.Column('modality', sa.Text(), nullable=False),
    sa.Column('biomarkers', sa.Text(), nullable=False),
    sa.Column('commercial_precedent', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_slug'), 'candidates', ['slug'], unique=True)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_slug', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_slug', sa.String(length=32), nullable=False),
    sa.Column('allin_low_usd_k', sa.Float(), nullable=False),
    sa.Column('allin_high_usd_k', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_slug')
    )
    op.create_table('cro_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('capability_tags', sa.String(length=512), nullable=False),
    sa.Column('quality_systems', sa.String(length=256), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=False),
    sa.Column('contact_email', sa.String(length=256), nullable=False),
    sa.Column('verified_source', sa.String(length=512), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('integration_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('agent_key', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_key'), 'data_sources', ['key'], unique=True)
    op.create_table('genes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('uniprot_accession', sa.String(length=16), nullable=False),
    sa.Column('protein_name', sa.String(length=256), nullable=False),
    sa.Column('subunit_role', sa.String(length=256), nullable=False),
    sa.Column('organ_system', sa.String(length=256), nullable=False),
    sa.Column('inheritance', sa.String(length=128), nullable=False),
    sa.Column('omim', sa.String(length=256), nullable=False),
    sa.Column('disease', sa.Text(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=False),
    sa.Column('source_citation', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('in_top3', sa.Boolean(), nullable=False),
    sa.Column('xlsx_uniprot_claim', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genes_symbol'), 'genes', ['symbol'], unique=True)
    op.create_table('graph_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('properties_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_type', 'external_ref', name='uq_node_type_ref')
    )
    op.create_index(op.f('ix_graph_nodes_node_type'), 'graph_nodes', ['node_type'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('candidate_slug', sa.String(length=32), nullable=False),
    sa.Column('gene_symbol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('readiness_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_slug', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('requirement_key', sa.String(length=64), nullable=False),
    sa.Column('requirement_name', sa.String(length=256), nullable=False),
    sa.Column('evidence_status', sa.String(length=16), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=False),
    sa.Column('evidence_source_ref', sa.String(length=512), nullable=False),
    sa.Column('imported_from', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_requirements_candidate_slug'), 'readiness_requirements', ['candidate_slug'], unique=False)
    op.create_table('reagent_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('catalog_number', sa.String(length=64), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('reorder_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=256), nullable=False),
    sa.Column('genes', sa.String(length=128), nullable=False),
    sa.Column('commercial', sa.Float(), nullable=False),
    sa.Column('patients', sa.Float(), nullable=False),
    sa.Column('cmc', sa.Float(), nullable=False),
    sa.Column('feasibility', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('low_usd_k', sa.Float(), nullable=False),
    sa.Column('high_usd_k', sa.Float(), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('candidate_slug', sa.String(length=32), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('assay_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(length=48), nullable=False),
    sa.Column('properties_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_edge_type'), 'graph_edges', ['edge_type'], unique=False)
    op.create_table('hypothesis_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('from_label', sa.String(length=256), nullable=False),
    sa.Column('to_label', sa.String(length=256), nullable=False),
    sa.Column('supporting_papers_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('conflicting_evidence', sa.Text(), nullable=False),
    sa.Column('experimental_status', sa.String(length=24), nullable=False),
    sa.Column('recommended_next_experiment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('candidate_slug', sa.String(length=32), nullable=False),
    sa.Column('study_type', sa.String(length=128), nullable=False),
    sa.Column('cro_vendor_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('target_start_date', sa.String(length=16), nullable=False),
    sa.Column('target_end_date', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cro_vendor_id'], ['cro_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('month_label', sa.String(length=32), nullable=False),
    sa.Column('track', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('mutation', sa.String(length=32), nullable=False),
    sa.Column('wt_aa', sa.String(length=4), nullable=False),
    sa.Column('mut_aa', sa.String(length=4), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('phenotype_severity', sa.String(length=32), nullable=False),
    sa.Column('mechanism_class', sa.String(length=64), nullable=False),
    sa.Column('degradation_risk', sa.String(length=32), nullable=False),
    sa.Column('conservation_score', sa.Float(), nullable=False),
    sa.Column('predicted_delta_g', sa.Float(), nullable=False),
    sa.Column('structural_region', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('study_type', sa.String(length=128), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('turnaround_days', sa.Integer(), nullable=False),
    sa.Column('quote_date', sa.String(length=16), nullable=False),
    sa.Column('quote_document_ref', sa.String(length=512), nullable=False),
    sa.Column('imported_from', sa.String(length=256), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['cro_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assay_acceptance_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('assay_name', sa.String(length=128), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('comparator', sa.String(length=8), nullable=False),
    sa.Column('threshold_low', sa.Float(), nullable=True),
    sa.Column('threshold_high', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('imported_from', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assay_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('assay_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('file_ref', sa.String(length=512), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('go_no_go_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('system_recommendation', sa.String(length=16), nullable=False),
    sa.Column('system_rationale', sa.Text(), nullable=False),
    sa.Column('system_measured_candidate_score', sa.Float(), nullable=True),
    sa.Column('system_assay_acceptance_pass_rate', sa.Float(), nullable=True),
    sa.Column('system_budget_status', sa.String(length=16), nullable=False),
    sa.Column('system_timeline_status', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('human_decision', sa.String(length=16), nullable=False),
    sa.Column('human_reviewer', sa.String(length=128), nullable=False),
    sa.Column('human_decision_at', sa.DateTime(), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notebook_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('sample_id_external', sa.String(length=128), nullable=False),
    sa.Column('sample_type', sa.String(length=128), nullable=False),
    sa.Column('current_location', sa.String(length=256), nullable=False),
    sa.Column('current_custodian', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('imported_from', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('budgeted_usd', sa.Float(), nullable=False),
    sa.Column('actual_usd', sa.Float(), nullable=False),
    sa.Column('imported_from', sa.String(length=256), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('target_date', sa.String(length=16), nullable=False),
    sa.Column('actual_date', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('risk_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assay_acceptance_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('auto_evaluated', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['assay_acceptance_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_of_custody_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('from_custodian', sa.String(length=128), nullable=False),
    sa.Column('to_custodian', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol_execution_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_execution_steps')
    op.drop_table('chain_of_custody_events')
    op.drop_table('assay_acceptance_evaluations')
    op.drop_table('study_milestones')
    op.drop_table('study_costs')
    op.drop_table('samples')
    op.drop_table('protocols')
    op.drop_table('notebook_entries')
    op.drop_table('go_no_go_decisions')
    op.drop_table('assay_results')
    op.drop_table('assay_acceptance_criteria')
    op.drop_table('vendor_quotes')
    op.drop_table('variants')
    op.drop_table('timeline_items')
    op.drop_table('studies')
    op.drop_table('hypothesis_steps')
    op.drop_index(op.f('ix_graph_edges_edge_type'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_table('experiments')
    op.drop_table('cost_items')
    op.drop_table('scoring_candidates')
    op.drop_table('reagent_items')
    op.drop_index(op.f('ix_readiness_requirements_candidate_slug'), table_name='readiness_requirements')
    op.drop_table('readiness_requirements')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_graph_nodes_node_type'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_genes_symbol'), table_name='genes')
    op.drop_table('genes')
    op.drop_index(op.f('ix_data_sources_key'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_table('cro_vendors')
    op.drop_table('cost_summaries')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_candidates_slug'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_definitions_key'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_division'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
