"""
Seed data for CADDTARD OS v3.0. Extends the v2.0 six-layer seed (data
sources, agent definitions, knowledge graph, hypotheses) with eight new
real-live-data agents added in v3.0 (Europe PMC, openFDA, DailyMed, NIH
RePORTER, WHO GHO, Reactome, PubChem, PatentsView) plus their DataSource
registry rows. The two rows that used to carry key=europepmc/reactome as
"planned" placeholders were removed rather than duplicated once those
sources actually went live in v3.0. Everything below this docstring is
data, not logic - the actual HTTP calls live in app/agents/*.py.
"""

DATA_SOURCES = [{'agent_key': '',
  'category': 'genomics',
  'description': 'Clinical variant classification. Used as a citation source in the v2 gene reference table; '
                 'not yet polled live.',
  'integration_type': 'rest_api',
  'key': 'clinvar',
  'name': 'ClinVar',
  'status': 'planned',
  'url': 'https://www.ncbi.nlm.nih.gov/clinvar/'},
 {'agent_key': 'population_genetics',
  'category': 'genomics',
  'description': 'Population allele frequency + constraint metrics.',
  'integration_type': 'graphql',
  'key': 'gnomad',
  'name': 'gnomAD',
  'status': 'connected',
  'url': 'https://gnomad.broadinstitute.org/'},
 {'agent_key': 'genomics',
  'category': 'genomics',
  'description': 'Protein sequence/accession cross-checking.',
  'integration_type': 'rest_api',
  'key': 'uniprot',
  'name': 'UniProt',
  'status': 'connected',
  'url': 'https://www.uniprot.org/'},
 {'agent_key': 'gene_transcript',
  'category': 'genomics',
  'description': 'Gene/transcript metadata.',
  'integration_type': 'rest_api',
  'key': 'ensembl',
  'name': 'Ensembl',
  'status': 'connected',
  'url': 'https://rest.ensembl.org/'},
 {'agent_key': '',
  'category': 'genomics',
  'description': 'Gene records; not yet polled independently of PubMed/UniProt.',
  'integration_type': 'rest_api',
  'key': 'ncbi_gene',
  'name': 'NCBI Gene',
  'status': 'planned',
  'url': 'https://www.ncbi.nlm.nih.gov/gene/'},
 {'agent_key': '',
  'category': 'clinical',
  'description': 'Curated Mendelian phenotype-gene relationships; no free public API, cited manually in the '
                 'gene reference table.',
  'integration_type': 'file',
  'key': 'omim',
  'name': 'OMIM',
  'status': 'planned',
  'url': 'https://omim.org/'},
 {'agent_key': 'literature',
  'category': 'literature',
  'description': 'Literature surveillance via NCBI E-utilities.',
  'integration_type': 'rest_api',
  'key': 'pubmed',
  'name': 'PubMed',
  'status': 'connected',
  'url': 'https://pubmed.ncbi.nlm.nih.gov/'},
 {'agent_key': 'clinical_trials',
  'category': 'clinical',
  'description': 'Registered trial counts per disease area.',
  'integration_type': 'rest_api',
  'key': 'clinicaltrials',
  'name': 'ClinicalTrials.gov',
  'status': 'connected',
  'url': 'https://clinicaltrials.gov/'},
 {'agent_key': 'competitive_intelligence',
  'category': 'clinical',
  'description': 'Target-disease association and tractability evidence.',
  'integration_type': 'graphql',
  'key': 'opentargets',
  'name': 'Open Targets',
  'status': 'connected',
  'url': 'https://platform.opentargets.org/'},
 {'agent_key': 'small_molecule',
  'category': 'chemistry',
  'description': 'Bioactive small-molecule chemical matter.',
  'integration_type': 'rest_api',
  'key': 'chembl',
  'name': 'ChEMBL',
  'status': 'connected',
  'url': 'https://www.ebi.ac.uk/chembl/'},
 {'agent_key': '',
  'category': 'chemistry',
  'description': 'Licensed drug database; requires a commercial license, not queried live.',
  'integration_type': 'file',
  'key': 'drugbank',
  'name': 'DrugBank',
  'status': 'planned',
  'url': 'https://go.drugbank.com/'},
 {'agent_key': 'structure_prediction',
  'category': 'structure',
  'description': 'Predicted per-chain protein structures.',
  'integration_type': 'rest_api',
  'key': 'alphafold',
  'name': 'AlphaFold',
  'status': 'connected',
  'url': 'https://alphafold.ebi.ac.uk/'},
 {'agent_key': 'structural',
  'category': 'structure',
  'description': 'Experimental (cryo-EM/crystal) structures.',
  'integration_type': 'rest_api',
  'key': 'pdb',
  'name': 'PDB',
  'status': 'connected',
  'url': 'https://www.rcsb.org/'},
 {'agent_key': '',
  'category': 'expression',
  'description': 'Tissue-level expression atlas.',
  'integration_type': 'rest_api',
  'key': 'gtex',
  'name': 'GTEx',
  'status': 'planned',
  'url': 'https://gtexportal.org/'},
 {'agent_key': '',
  'category': 'expression',
  'description': 'Single-cell reference atlas.',
  'integration_type': 'rest_api',
  'key': 'hca',
  'name': 'Human Cell Atlas',
  'status': 'planned',
  'url': 'https://www.humancellatlas.org/'},
 {'agent_key': '',
  'category': 'functional_genomics',
  'description': 'Cancer cell line dependency screens.',
  'integration_type': 'file',
  'key': 'depmap',
  'name': 'DepMap',
  'status': 'planned',
  'url': 'https://depmap.org/'},
 {'agent_key': '',
  'category': 'network',
  'description': 'Protein-protein interaction network.',
  'integration_type': 'rest_api',
  'key': 'string',
  'name': 'STRING',
  'status': 'planned',
  'url': 'https://string-db.org/'},
 {'agent_key': '',
  'category': 'pathway',
  'description': 'Pathway/genome database.',
  'integration_type': 'rest_api',
  'key': 'kegg',
  'name': 'KEGG',
  'status': 'planned',
  'url': 'https://www.kegg.jp/'},
 {'agent_key': '',
  'category': 'regulatory',
  'description': 'US regulatory filings/guidance; no unified structured API.',
  'integration_type': 'file',
  'key': 'fda',
  'name': 'FDA',
  'status': 'planned',
  'url': 'https://www.fda.gov/'},
 {'agent_key': '',
  'category': 'regulatory',
  'description': 'EU regulatory filings/guidance; no unified structured API.',
  'integration_type': 'file',
  'key': 'ema',
  'name': 'EMA',
  'status': 'planned',
  'url': 'https://www.ema.europa.eu/'},
 {'agent_key': 'github_watch',
  'category': 'software',
  'description': 'Public repository search for research tooling.',
  'integration_type': 'rest_api',
  'key': 'github',
  'name': 'GitHub',
  'status': 'connected',
  'url': 'https://github.com/'},
 {'agent_key': '',
  'category': 'literature',
  'description': 'Life-science preprints.',
  'integration_type': 'rest_api',
  'key': 'biorxiv',
  'name': 'BioRxiv',
  'status': 'planned',
  'url': 'https://www.biorxiv.org/'},
 {'agent_key': '',
  'category': 'literature',
  'description': 'Clinical/health preprints.',
  'integration_type': 'rest_api',
  'key': 'medrxiv',
  'name': 'MedRxiv',
  'status': 'planned',
  'url': 'https://www.medrxiv.org/'},
 {'agent_key': '',
  'category': 'internal',
  'description': 'Captured via Layer 5 Lab OS today (manual entry); automated pipeline ingestion is future '
                 'work.',
  'integration_type': 'internal',
  'key': 'internal_lab_data',
  'name': 'Internal laboratory data',
  'status': 'planned',
  'url': ''},
 {'agent_key': '',
  'category': 'internal',
  'description': 'Electronic lab notebooks - modeled by NotebookEntry in Layer 5; no external ELN vendor '
                 'integration yet.',
  'integration_type': 'internal',
  'key': 'elns',
  'name': 'ELNs',
  'status': 'planned',
  'url': ''},
 {'agent_key': '',
  'category': 'internal',
  'description': 'Laboratory information management; ReagentItem/Experiment models exist in Layer 5, no '
                 'vendor LIMS integration yet.',
  'integration_type': 'internal',
  'key': 'lims',
  'name': 'LIMS',
  'status': 'planned',
  'url': ''},
 {'agent_key': '',
  'category': 'internal',
  'description': 'AssayResult (assay_type=sequencing) models the record; no automated pipeline hookup yet.',
  'integration_type': 'internal',
  'key': 'sequencing_pipelines',
  'name': 'Sequencing pipelines',
  'status': 'planned',
  'url': ''},
 {'agent_key': '',
  'category': 'internal',
  'description': 'AssayResult (assay_type=microscopy) models the record; no instrument integration yet.',
  'integration_type': 'internal',
  'key': 'imaging_systems',
  'name': 'Imaging systems',
  'status': 'planned',
  'url': ''},
 {'agent_key': '',
  'category': 'internal',
  'description': 'AssayResult (assay_type=lc_ms and others) models the record; no instrument integration '
                 'yet.',
  'integration_type': 'internal',
  'key': 'omics_platforms',
  'name': 'Omics platforms',
  'status': 'planned',
  'url': ''},
 {'agent_key': 'ontology',
  'category': 'pathway',
  'description': 'GO term definitions - added beyond the original source list; serves the same pathway-layer '
                 'ambition as Reactome/KEGG with a source we could actually implement live.',
  'integration_type': 'rest_api',
  'key': 'quickgo',
  'name': 'QuickGO / Gene Ontology',
  'status': 'connected',
  'url': 'https://www.ebi.ac.uk/QuickGO/'},
 {'agent_key': 'disease_phenotype',
  'category': 'clinical',
  'description': 'Cross-species disease/phenotype knowledge graph - added beyond the original source list.',
  'integration_type': 'rest_api',
  'key': 'monarch',
  'name': 'Monarch Initiative',
  'status': 'connected',
  'url': 'https://monarchinitiative.org/'},
 {'agent_key': 'europepmc_literature',
  'category': 'literature',
  'description': 'EBI literature search including preprints; used for real-time preprint coverage the PubMed '
                 'agent misses.',
  'integration_type': 'rest_api',
  'key': 'europepmc',
  'name': 'Europe PMC',
  'status': 'connected',
  'url': 'https://www.ebi.ac.uk/europepmc/webservices/rest/'},
 {'agent_key': 'regulatory_precedent',
  'category': 'regulatory',
  'description': 'FDA structured product labels and enforcement actions, live query, no API key required.',
  'integration_type': 'rest_api',
  'key': 'openfda',
  'name': 'openFDA',
  'status': 'connected',
  'url': 'https://api.fda.gov/'},
 {'agent_key': 'cmc_product_label',
  'category': 'regulatory',
  'description': 'NIH structured product label repository; source of record for approved '
                 'formulation/dosage-form data.',
  'integration_type': 'rest_api',
  'key': 'dailymed',
  'name': 'DailyMed',
  'status': 'connected',
  'url': 'https://dailymed.nlm.nih.gov/dailymed/services/v2/'},
 {'agent_key': 'funding_opportunities',
  'category': 'regulatory',
  'description': 'NIH federal grant award search API; live revealed-preference funding signal per disease '
                 'term.',
  'integration_type': 'rest_api',
  'key': 'nih_reporter',
  'name': 'NIH RePORTER',
  'status': 'connected',
  'url': 'https://api.reporter.nih.gov/'},
 {'agent_key': 'who_burden',
  'category': 'genomics',
  'description': 'WHO OData burden/indicator API, live query by indicator name.',
  'integration_type': 'rest_api',
  'key': 'who_gho',
  'name': 'WHO Global Health Observatory',
  'status': 'connected',
  'url': 'https://ghoapi.azureedge.net/api/'},
 {'agent_key': 'pathway_intelligence',
  'category': 'pathway',
  'description': 'Curated human pathway database, live search by mechanistic term.',
  'integration_type': 'rest_api',
  'key': 'reactome',
  'name': 'Reactome',
  'status': 'connected',
  'url': 'https://reactome.org/ContentService/'},
 {'agent_key': 'compound_properties',
  'category': 'chemistry',
  'description': 'NIH chemistry database; live compound property lookup (formula, MW, SMILES).',
  'integration_type': 'rest_api',
  'key': 'pubchem',
  'name': 'PubChem',
  'status': 'connected',
  'url': 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/'},
 {'agent_key': 'patent_landscape',
  'category': 'regulatory',
  'description': 'US patent full-text search; key-gated since 2024. Agent is implemented and runs live once '
                 'PATENTSVIEW_API_KEY is set; otherwise reports "not configured" honestly.',
  'integration_type': 'rest_api',
  'key': 'patentsview',
  'name': 'PatentsView',
  'status': 'partial',
  'url': 'https://search.patentsview.org/'}]

AGENT_DEFINITIONS = [{'description': 'Cross-checks UniProt accessions for the top-3 program genes live against rest.uniprot.org '
                 'and flags mismatches (this is how the ATP6V0A4 accession error was originally caught).',
  'division': 'Genomics',
  'interval_minutes': 360,
  'key': 'genomics',
  'module_path': 'app.agents:genomics',
  'name': 'Variant Agent',
  'status': 'implemented'},
 {'description': 'Live gene metadata (biotype, transcript count) from Ensembl REST, resolved by symbol at '
                 'call time.',
  'division': 'Genomics',
  'interval_minutes': 1440,
  'key': 'gene_transcript',
  'module_path': 'app.agents:gene_transcript',
  'name': 'Gene Agent',
  'status': 'implemented'},
 {'description': 'Dedicated isoform/transcript-consequence agent; transcript counts are currently included '
                 'in the Gene Agent response above.',
  'division': 'Genomics',
  'interval_minutes': None,
  'key': 'genomics_transcript_agent_planned',
  'module_path': '',
  'name': 'Transcript Agent',
  'status': 'planned'},
 {'description': 'Domain/PTM-level protein annotation beyond accession validation; UniProt accession '
                 'checking is live via the Variant Agent today.',
  'division': 'Genomics',
  'interval_minutes': None,
  'key': 'genomics_protein_agent_planned',
  'module_path': '',
  'name': 'Protein Agent',
  'status': 'planned'},
 {'description': 'Isoform-specific expression/consequence modeling.',
  'division': 'Genomics',
  'interval_minutes': None,
  'key': 'genomics_isoform_agent_planned',
  'module_path': '',
  'name': 'Isoform Agent',
  'status': 'planned'},
 {'description': 'Cross-species conservation/orthology analysis.',
  'division': 'Genomics',
  'interval_minutes': None,
  'key': 'genomics_evolution_agent_planned',
  'module_path': '',
  'name': 'Evolution Agent',
  'status': 'planned'},
 {'description': 'Live gnomAD constraint metrics (pLI, o/e LoF, o/e missense) per top-3 gene via the public '
                 'gnomAD GraphQL API.',
  'division': 'Genomics',
  'interval_minutes': 1440,
  'key': 'population_genetics',
  'module_path': 'app.agents:population_genetics',
  'name': 'Population Genetics Agent',
  'status': 'implemented'},
 {'description': 'Live disease/phenotype term resolution via the Monarch Initiative API.',
  'division': 'Disease Biology',
  'interval_minutes': 720,
  'key': 'disease_phenotype',
  'module_path': 'app.agents:disease_phenotype',
  'name': 'Disease Agent',
  'status': 'implemented'},
 {'description': 'Structured phenotype (HPO term) extraction; served jointly by the Disease Agent today.',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_phenotype_agent_planned',
  'module_path': '',
  'name': 'Phenotype Agent',
  'status': 'planned'},
 {'description': 'Longitudinal natural-history data aggregation - no structured public API identified for '
                 'these diseases.',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_natural_history_agent_planned',
  'module_path': '',
  'name': 'Natural History Agent',
  'status': 'planned'},
 {'description': 'Histopathology/imaging correlate agent.',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_pathology_agent_planned',
  'module_path': '',
  'name': 'Pathology Agent',
  'status': 'planned'},
 {'description': 'General cell-biology assay interpretation agent.',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_cell_biology_agent_planned',
  'module_path': '',
  'name': 'Cell Biology Agent',
  'status': 'planned'},
 {'description': 'Lysosomal-pathway-specific evidence aggregation; GO lysosome terms are queryable today via '
                 'the Gene Ontology Agent.',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_lysosome_agent_planned',
  'module_path': '',
  'name': 'Lysosome Agent',
  'status': 'planned'},
 {'description': 'Autophagy-pathway-specific evidence aggregation.',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_autophagy_agent_planned',
  'module_path': '',
  'name': 'Autophagy Agent',
  'status': 'planned'},
 {'description': 'Mitochondrial-pathway-specific evidence aggregation.',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_mitochondria_agent_planned',
  'module_path': '',
  'name': 'Mitochondria Agent',
  'status': 'planned'},
 {'description': 'Immune-pathway-specific evidence aggregation (relevant to ATP6AP1/ATP6AP2 immunodeficiency '
                 'phenotypes outside the current top-3).',
  'division': 'Disease Biology',
  'interval_minutes': None,
  'key': 'disease_biology_immune_biology_agent_planned',
  'module_path': '',
  'name': 'Immune Biology Agent',
  'status': 'planned'},
 {'description': 'Guide RNA design and on/off-target prediction - requires a licensed or self-hosted design '
                 'model.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_crispr_agent_planned',
  'module_path': '',
  'name': 'CRISPR Agent',
  'status': 'planned'},
 {'description': 'pegRNA design agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_prime_editing_agent_planned',
  'module_path': '',
  'name': 'Prime Editing Agent',
  'status': 'planned'},
 {'description': 'Base editor window/bystander-edit prediction agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_base_editing_agent_planned',
  'module_path': '',
  'name': 'Base Editing Agent',
  'status': 'planned'},
 {'description': 'ADAR-mediated RNA editing design agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_rna_editing_agent_planned',
  'module_path': '',
  'name': 'RNA Editing Agent',
  'status': 'planned'},
 {'description': "Antisense oligonucleotide sequence design/off-target screening - the ATP6V0C program's "
                 'lead modality; design tooling is future work, the commercial/mechanism rationale is '
                 'already captured in the Candidate profile.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_aso_agent_planned',
  'module_path': '',
  'name': 'ASO Agent',
  'status': 'planned'},
 {'description': 'siRNA design/off-target screening agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_sirna_agent_planned',
  'module_path': '',
  'name': 'siRNA Agent',
  'status': 'planned'},
 {'description': 'Enzyme/protein replacement feasibility agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_protein_replacement_agent_planned',
  'module_path': '',
  'name': 'Protein Replacement Agent',
  'status': 'planned'},
 {'description': 'AAV capsid/promoter selection agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_aav_agent_planned',
  'module_path': '',
  'name': 'AAV Agent',
  'status': 'planned'},
 {'description': 'Lipid nanoparticle formulation agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_lnp_agent_planned',
  'module_path': '',
  'name': 'LNP Agent',
  'status': 'planned'},
 {'description': 'Extracellular vesicle delivery agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_ev_agent_planned',
  'module_path': '',
  'name': 'EV Agent',
  'status': 'planned'},
 {'description': 'Live ChEMBL search for known V-ATPase-relevant chemical matter '
                 '(bafilomycin/concanamycin-class inhibitors).',
  'division': 'Therapeutics',
  'interval_minutes': 1440,
  'key': 'small_molecule',
  'module_path': 'app.agents:small_molecule',
  'name': 'Small Molecule Agent',
  'status': 'implemented'},
 {'description': 'Targeted protein degrader design agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_protac_agent_planned',
  'module_path': '',
  'name': 'PROTAC Agent',
  'status': 'planned'},
 {'description': 'Molecular glue degrader design agent.',
  'division': 'Therapeutics',
  'interval_minutes': None,
  'key': 'therapeutics_molecular_glue_agent_planned',
  'module_path': '',
  'name': 'Molecular Glue Agent',
  'status': 'planned'},
 {'description': "Live AlphaFold DB predicted-model metadata per top-3 gene's protein product.",
  'division': 'AI Science',
  'interval_minutes': 1440,
  'key': 'structure_prediction',
  'module_path': 'app.agents:structure_prediction',
  'name': 'Structure Prediction Agent',
  'status': 'implemented'},
 {'description': 'Ligand docking agent - needs GPU compute, out of scope for this environment.',
  'division': 'AI Science',
  'interval_minutes': None,
  'key': 'ai_science_docking_agent_planned',
  'module_path': '',
  'name': 'Docking Agent',
  'status': 'planned'},
 {'description': 'MD simulation orchestration agent - needs GPU/HPC compute.',
  'division': 'AI Science',
  'interval_minutes': None,
  'key': 'ai_science_molecular_dynamics_agent_planned',
  'module_path': '',
  'name': 'Molecular Dynamics Agent',
  'status': 'planned'},
 {'description': 'ML-based binding affinity prediction agent.',
  'division': 'AI Science',
  'interval_minutes': None,
  'key': 'ai_science_binding_prediction_agent_planned',
  'module_path': '',
  'name': 'Binding Prediction Agent',
  'status': 'planned'},
 {'description': 'In silico ADME prediction agent.',
  'division': 'AI Science',
  'interval_minutes': None,
  'key': 'ai_science_adme_agent_planned',
  'module_path': '',
  'name': 'ADME Agent',
  'status': 'planned'},
 {'description': 'Pharmacokinetic/pharmacodynamic modeling agent.',
  'division': 'AI Science',
  'interval_minutes': None,
  'key': 'ai_science_pk/pd_agent_planned',
  'module_path': '',
  'name': 'PK/PD Agent',
  'status': 'planned'},
 {'description': 'Omics-driven biomarker discovery agent.',
  'division': 'AI Science',
  'interval_minutes': None,
  'key': 'ai_science_biomarker_discovery_agent_planned',
  'module_path': '',
  'name': 'Biomarker Discovery Agent',
  'status': 'planned'},
 {'description': 'Genotype/phenotype-driven trial stratification agent.',
  'division': 'AI Science',
  'interval_minutes': None,
  'key': 'ai_science_patient_stratification_agent_planned',
  'module_path': '',
  'name': 'Patient Stratification Agent',
  'status': 'planned'},
 {'description': 'Automated assay-protocol drafting agent; Protocol records exist in Layer 5 today for '
                 'manual entry.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_assay_design_agent_planned',
  'module_path': '',
  'name': 'Assay Design Agent',
  'status': 'planned'},
 {'description': 'CMC package tracking agent; cost/timeline estimates exist today in the Candidate profiles.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_cmc_agent_planned',
  'module_path': '',
  'name': 'CMC Agent',
  'status': 'planned'},
 {'description': 'Analytical method tracking agent.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_analytical_development_agent_planned',
  'module_path': '',
  'name': 'Analytical Development Agent',
  'status': 'planned'},
 {'description': 'QMS/deviation tracking agent.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_quality_systems_agent_planned',
  'module_path': '',
  'name': 'Quality Systems Agent',
  'status': 'planned'},
 {'description': 'Regulatory milestone tracking agent; IND-readiness checklist exists today (Layer 6).',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_regulatory_agent_planned',
  'module_path': '',
  'name': 'Regulatory Agent',
  'status': 'planned'},
 {'description': 'Live ClinicalTrials.gov registered-trial counts per disease-area search term.',
  'division': 'Development',
  'interval_minutes': 1440,
  'key': 'clinical_trials',
  'module_path': 'app.agents:clinical_trials',
  'name': 'Clinical Agent',
  'status': 'implemented'},
 {'description': 'Market-sizing/pricing agent - no licensed market-research data source connected.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_commercial_agent_planned',
  'module_path': '',
  'name': 'Commercial Agent',
  'status': 'planned'},
 {'description': 'Live Open Targets Platform target search per top-3 gene.',
  'division': 'Development',
  'interval_minutes': 1440,
  'key': 'competitive_intelligence',
  'module_path': 'app.agents:competitive_intelligence',
  'name': 'Competitive Intelligence Agent',
  'status': 'implemented'},
 {'description': 'The 10-program scoring rubric (commercial/patients/CMC/feasibility) is already live today '
                 'via GET /api/scoring; a continuously re-scoring agent version is future work.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_portfolio_optimization_agent_planned',
  'module_path': '',
  'name': 'Portfolio Optimization Agent',
  'status': 'planned'},
 {'description': 'Grant-application drafting agent.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_grant_writing_agent_planned',
  'module_path': '',
  'name': 'Grant Writing Agent',
  'status': 'planned'},
 {'description': 'Investor update drafting agent.',
  'division': 'Development',
  'interval_minutes': None,
  'key': 'development_investor_relations_agent_planned',
  'module_path': '',
  'name': 'Investor Relations Agent',
  'status': 'planned'},
 {'description': 'Live PubMed hit counts per top-3 gene via NCBI E-utilities. Predates this taxonomy (built '
                 'in v1); kept as-is.',
  'division': 'Evidence & Infrastructure',
  'interval_minutes': 720,
  'key': 'literature',
  'module_path': 'app.agents:literature',
  'name': 'Literature Surveillance Agent',
  'status': 'implemented'},
 {'description': 'Live resolution metadata for the human V-ATPase cryo-EM entries via the RCSB PDB Data API. '
                 'Predates this taxonomy (built in v1); complements the AI Science Structure Prediction '
                 'Agent (AlphaFold) with experimental structures.',
  'division': 'Evidence & Infrastructure',
  'interval_minutes': 1440,
  'key': 'structural',
  'module_path': 'app.agents:structural',
  'name': 'Structural Biology Agent',
  'status': 'implemented'},
 {'description': 'Live GO term definitions via EBI QuickGO. Predates this taxonomy (built in v1); serves the '
                 'pathway-layer ambition alongside the planned Reactome/KEGG sources.',
  'division': 'Evidence & Infrastructure',
  'interval_minutes': 1440,
  'key': 'ontology',
  'module_path': 'app.agents:ontology',
  'name': 'Gene Ontology Agent',
  'status': 'implemented'},
 {'description': 'Live public GitHub repository search for V-ATPase-relevant research tooling.',
  'division': 'Evidence & Infrastructure',
  'interval_minutes': 4320,
  'key': 'github_watch',
  'module_path': 'app.agents:github_watch',
  'name': 'GitHub Watch Agent',
  'status': 'implemented'},
 {'description': 'Live Europe PMC search (preprints + MEDLINE) across all portfolio disease terms (V-ATPase '
                 'rare diseases + NTDs); complements the PubMed-only Literature Agent with preprint '
                 'coverage.',
  'division': 'Evidence & Infrastructure',
  'interval_minutes': 360,
  'key': 'europepmc_literature',
  'module_path': 'app.agents.literature_ext_agent',
  'name': 'Europe PMC Literature Agent',
  'status': 'implemented'},
 {'description': 'Live openFDA structured-product-label and enforcement lookups per repurposing candidate - '
                 'is there already an FDA-approved label to lean on for a 505(b)(2) pathway.',
  'division': 'Development',
  'interval_minutes': 1440,
  'key': 'regulatory_precedent',
  'module_path': 'app.agents.regulatory_agents:run_regulatory_precedent',
  'name': 'Regulatory Precedent Agent',
  'status': 'implemented'},
 {'description': 'Live DailyMed structured product label lookup per repurposing candidate - the direct '
                 'source record for existing approved formulation/dosage-form data, feeding the CMC '
                 'readiness layer.',
  'division': 'Development',
  'interval_minutes': 1440,
  'key': 'cmc_product_label',
  'module_path': 'app.agents.regulatory_agents:run_cmc_product_label',
  'name': 'CMC Product Label Agent',
  'status': 'implemented'},
 {'description': 'Live NIH RePORTER search for active/recent US federal awards per portfolio disease term - '
                 'real revealed-preference funding signal, not a manually maintained list.',
  'division': 'Development',
  'interval_minutes': 1440,
  'key': 'funding_opportunities',
  'module_path': 'app.agents.funding_agents',
  'name': 'Funding Opportunities Agent',
  'status': 'implemented'},
 {'description': 'Live WHO Global Health Observatory indicator search per portfolio disease term; explicitly '
                 'reports when WHO has not defined a named burden indicator (true for most ultra-neglected '
                 'NTDs), which is itself a diligence finding.',
  'division': 'Disease Biology',
  'interval_minutes': 2880,
  'key': 'who_burden',
  'module_path': 'app.agents.burden_agent',
  'name': 'WHO Burden Agent',
  'status': 'implemented'},
 {'description': 'Live Reactome ContentService search for curated human pathways matching each mechanistic '
                 'hypothesis term in the portfolio (lysosomal acidification, melanin biosynthesis, fungal '
                 'cell wall biosynthesis, Th17 differentiation).',
  'division': 'Genomics',
  'interval_minutes': 1440,
  'key': 'pathway_intelligence',
  'module_path': 'app.agents.pathway_ext_agent',
  'name': 'Pathway Intelligence Agent',
  'status': 'implemented'},
 {'description': 'Live PubChem PUG REST chemistry record (formula, MW, canonical SMILES) per repurposing '
                 'candidate compound.',
  'division': 'Therapeutics',
  'interval_minutes': 2880,
  'key': 'compound_properties',
  'module_path': 'app.agents.compound_agent',
  'name': 'Compound Properties Agent',
  'status': 'implemented'},
 {'description': 'PatentsView Search API per repurposing candidate. Requires a free PATENTSVIEW_API_KEY '
                 '(PatentsView is key-gated since 2024); runs the real live query when configured, otherwise '
                 'honestly reports "not configured" rather than fabricating a patent landscape.',
  'division': 'Development',
  'interval_minutes': 4320,
  'key': 'patent_landscape',
  'module_path': 'app.agents.patent_agent',
  'name': 'Patent Landscape Agent',
  'status': 'implemented'}]

GRAPH_NODES = [{'external_ref': 'GO:0033176',
  'label': 'V-ATPase proton-transport pathway',
  'node_type': 'pathway',
  'properties': {'description': 'Proton-transporting V-type ATPase complex (GO:0033176)'}},
 {'external_ref': 'UniProt:Q9HBG4',
  'label': 'ATP6V0A4',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal recessive',
                 'organ': 'Renal / auditory',
                 'protein_name': 'V-type proton ATPase 116 kDa subunit a4'}},
 {'external_ref': 'OMIM:Gene 602722 · Phenotype 267300 (DRTA2)',
  'label': 'Distal renal tubular acidosis (dRTA), with or without progressive sensorineural hearing loss',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 602722 · Phenotype 267300 (DRTA2)'}},
 {'external_ref': 'UniProt:Q9Y487',
  'label': 'ATP6V0A2',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal recessive',
                 'organ': 'Dermatologic / connective tissue / Golgi glycosylation',
                 'protein_name': 'V-type proton ATPase 116 kDa subunit a2'}},
 {'external_ref': 'OMIM:Gene 611716 · Phenotype 219200 (ARCL2A)',
  'label': 'Cutis laxa type IIA / ARCL2A (wrinkly skin syndrome) with N- and O-glycosylation defects',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 611716 · Phenotype 219200 (ARCL2A)'}},
 {'external_ref': 'UniProt:P15313',
  'label': 'ATP6V1B1',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal recessive',
                 'organ': 'Renal / auditory',
                 'protein_name': 'V-type proton ATPase subunit B, kidney isoform'}},
 {'external_ref': 'OMIM:Gene 192132 · Phenotype 267300',
  'label': 'Distal renal tubular acidosis with early-onset sensorineural hearing loss (DRTA1)',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 192132 · Phenotype 267300'}},
 {'external_ref': 'UniProt:P38606',
  'label': 'ATP6V1A',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal dominant (DEE93, usually de novo) / autosomal recessive (cutis '
                                'laxa)',
                 'organ': 'Neurodevelopmental / epilepsy; also dermatologic-connective tissue',
                 'protein_name': 'V-type proton ATPase catalytic subunit A'}},
 {'external_ref': 'OMIM:Gene 607027 · Phenotype 618012 (DEE93)',
  'label': 'Developmental and epileptic encephalopathy 93 (DEE93); also autosomal-recessive cutis laxa type '
           'IID',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 607027 · Phenotype 618012 (DEE93)'}},
 {'external_ref': 'UniProt:P36543',
  'label': 'ATP6V1E1',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal recessive',
                 'organ': 'Dermatologic / connective tissue',
                 'protein_name': 'V-type proton ATPase subunit E1'}},
 {'external_ref': 'OMIM:Gene 609150',
  'label': 'Autosomal-recessive cutis laxa type IIC (ARCL2C)',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 609150'}},
 {'external_ref': 'UniProt:P27449',
  'label': 'ATP6V0C',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal dominant (de novo)',
                 'organ': 'Neurodevelopmental / epilepsy',
                 'protein_name': 'V-type proton ATPase 16 kDa proteolipid subunit c'}},
 {'external_ref': 'OMIM:No stable phenotype MIM as of literature reviewed (2020-2021 cohort)',
  'label': 'Neurodevelopmental disorder with or without epilepsy (de novo heterozygous variants; '
           'haploinsufficiency in at least one reported case)',
  'node_type': 'disease',
  'properties': {'omim': 'No stable phenotype MIM as of literature reviewed (2020-2021 cohort)'}},
 {'external_ref': 'UniProt:P61421',
  'label': 'ATP6V0D1',
  'node_type': 'gene',
  'properties': {'inheritance': 'Not established',
                 'organ': 'Candidate: skeletal / osteoclast biology',
                 'protein_name': 'V-type proton ATPase subunit d1'}},
 {'external_ref': 'UniProt:O75348',
  'label': 'ATP6V1G1',
  'node_type': 'gene',
  'properties': {'inheritance': 'Not established',
                 'organ': 'Not established',
                 'protein_name': 'V-type proton ATPase subunit G1'}},
 {'external_ref': 'UniProt:Q3ZAQ7',
  'label': 'VMA21',
  'node_type': 'gene',
  'properties': {'inheritance': 'X-linked recessive',
                 'organ': 'Musculoskeletal (myopathy)',
                 'protein_name': 'Vacuolar ATPase assembly integral membrane protein VMA21'}},
 {'external_ref': 'OMIM:Phenotype 310440 (MEAX)',
  'label': 'X-linked myopathy with excessive autophagy (XMEA); VMA21-congenital disorder of glycosylation',
  'node_type': 'disease',
  'properties': {'omim': 'Phenotype 310440 (MEAX)'}},
 {'external_ref': 'UniProt:Q15904',
  'label': 'ATP6AP1',
  'node_type': 'gene',
  'properties': {'inheritance': 'X-linked recessive',
                 'organ': 'Immunologic / hepatic / glycosylation',
                 'protein_name': 'V-type proton ATPase subunit S1 (Ac45)'}},
 {'external_ref': 'OMIM:Gene 300197 · Phenotype 300972 (IMD47)',
  'label': 'Immunodeficiency 47 with hepatopathy (IMD47); ATP6AP1-congenital disorder of glycosylation (type '
           'IIs)',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 300197 · Phenotype 300972 (IMD47)'}},
 {'external_ref': 'UniProt:O75787',
  'label': 'ATP6AP2',
  'node_type': 'gene',
  'properties': {'inheritance': 'X-linked',
                 'organ': 'Neurologic (parkinsonism) / immunologic-hepatic / dermatologic',
                 'protein_name': 'Renin receptor / ATPase H+-transporting accessory protein 2'}},
 {'external_ref': 'OMIM:Gene 300556 · Phenotype 300911 (XPDS)',
  'label': 'X-linked parkinsonism with spasticity (XPDS); ATP6AP2-congenital disorder of glycosylation with '
           'liver disease, immunodeficiency and cutis laxa',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 300556 · Phenotype 300911 (XPDS)'}},
 {'external_ref': 'UniProt:Q13488',
  'label': 'TCIRG1',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal recessive',
                 'organ': 'Skeletal (osteoclast) / hematologic / can include CNS involvement',
                 'protein_name': 'V-type proton ATPase 116 kDa subunit a3'}},
 {'external_ref': 'OMIM:Gene 604592 · Phenotype 259700 (OPTB1)',
  'label': 'Autosomal-recessive osteopetrosis, infantile malignant form (~50% of ARO cases)',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 604592 · Phenotype 259700 (OPTB1)'}},
 {'external_ref': 'UniProt:Q86WC4',
  'label': 'OSTM1',
  'node_type': 'gene',
  'properties': {'inheritance': 'Autosomal recessive',
                 'organ': 'Skeletal + neurodegeneration',
                 'protein_name': 'Osteopetrosis-associated transmembrane protein 1 (chloride channel 7 beta '
                                 'subunit)'}},
 {'external_ref': 'OMIM:Gene 607649 · Phenotype 259720 (OPTB5)',
  'label': 'Autosomal-recessive osteopetrosis with primary neurodegeneration (OPTB5), most severe ARO '
           'subtype',
  'node_type': 'disease',
  'properties': {'omim': 'Gene 607649 · Phenotype 259720 (OPTB5)'}},
 {'external_ref': '',
  'label': 'Renal-targeted small-molecule V-ATPase corrector',
  'node_type': 'drug',
  'properties': {'status': 'candidate modality, top-3 program'}},
 {'external_ref': '',
  'label': 'TANGO-style splice-switching ASO (zorevunersen-class chemistry)',
  'node_type': 'drug',
  'properties': {'status': 'candidate modality, top-3 program'}},
 {'external_ref': '',
  'label': 'Ex vivo lentiviral HSC gene therapy (Zynteglo/Skysona-class modality)',
  'node_type': 'drug',
  'properties': {'status': 'candidate modality, top-3 program'}}]

GRAPH_EDGES = [['ATP6V0A4',
  'Distal renal tubular acidosis (dRTA), with or without progressive sensorineural hearing loss',
  'pathogenic_for',
  {'evidence': 'Molecular mechanisms of cutis laxa- and dRTA-causing mutations in V-ATPase a subunits, J '
               'Biol Chem 2018',
   'mechanism': 'Loss of proton translocation; ER retention and proteasomal/lysosomal degradation of '
                'missense variants'}],
 ['ATP6V0A4', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6V0A2',
  'Cutis laxa type IIA / ARCL2A (wrinkly skin syndrome) with N- and O-glycosylation defects',
  'pathogenic_for',
  {'evidence': 'A Novel ATP6V0A2 Mutation Causing Recessive Cutis Laxa, Genes 2019',
   'mechanism': 'Golgi pH dysregulation, impaired glycosylation, protein mistrafficking and degradation'}],
 ['ATP6V0A2', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6V1B1',
  'Distal renal tubular acidosis with early-onset sensorineural hearing loss (DRTA1)',
  'pathogenic_for',
  {'evidence': 'OMIM #267300 DRTA2',
   'mechanism': 'Loss of function; ~70% of patients show early-onset hearing loss vs ~39% for ATP6V0A4'}],
 ['ATP6V1B1', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6V1A',
  'Developmental and epileptic encephalopathy 93 (DEE93); also autosomal-recessive cutis laxa type IID',
  'pathogenic_for',
  {'evidence': 'Clinical and genetic characteristics of DEE93, Human Mutation 2024',
   'mechanism': 'Altered lysosomal homeostasis, abnormal neuritogenesis and synaptic density; both LOF and '
                'GOF variants reported at different residues'}],
 ['ATP6V1A', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6V1E1',
  'Autosomal-recessive cutis laxa type IIC (ARCL2C)',
  'pathogenic_for',
  {'evidence': 'Mutations in ATP6V1E1 or ATP6V1A Cause Autosomal-Recessive Cutis Laxa, AJHG 2020',
   'mechanism': 'Loss of function destabilizes V1 peripheral stalk assembly'}],
 ['ATP6V1E1', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6V0C',
  'Neurodevelopmental disorder with or without epilepsy (de novo heterozygous variants; haploinsufficiency '
  'in at least one reported case)',
  'pathogenic_for',
  {'evidence': 'Novel de novo mutation substantiates ATP6V0C as a gene causing epilepsy with intellectual '
               'disability, 2021',
   'mechanism': 'Impaired ATP6V0C-ATP6V0A subunit interaction; reduced RNA level in at least one patient '
                'consistent with haploinsufficiency'}],
 ['ATP6V0C', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6V0D1', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6V1G1', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['VMA21',
  'X-linked myopathy with excessive autophagy (XMEA); VMA21-congenital disorder of glycosylation',
  'pathogenic_for',
  {'evidence': 'VMA21 deficiency leads to autophagic dysregulation in XMEA, Acta Neuropathologica 2025; OMIM '
               '#310440',
   'mechanism': 'Reduced V-ATPase assembly efficiency lowers lysosomal V-ATPase content, raising lysosomal '
                'pH and partially blocking macroautophagy, causing vacuolation'}],
 ['VMA21', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6AP1',
  'Immunodeficiency 47 with hepatopathy (IMD47); ATP6AP1-congenital disorder of glycosylation (type IIs)',
  'pathogenic_for',
  {'evidence': 'ATP6AP1 deficiency causes an immunodeficiency with hepatopathy, Nat Commun 2016; OMIM '
               '#300972',
   'mechanism': 'Loss of function impairs V0 assembly and N-glycosylation of secreted/membrane proteins'}],
 ['ATP6AP1', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['ATP6AP2',
  'X-linked parkinsonism with spasticity (XPDS); ATP6AP2-congenital disorder of glycosylation with liver '
  'disease, immunodeficiency and cutis laxa',
  'pathogenic_for',
  {'evidence': 'Mutations in the X-linked ATP6AP2 cause a glycosylation disorder with autophagic defects, J '
               'Exp Med 2017; OMIM #300911',
   'mechanism': 'Hypomorphic missense variants cause tissue-specific hypoglycosylation and autophagy '
                'defects; more severe truncating variants cause the glycosylation/liver/immune syndrome'}],
 ['ATP6AP2', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['TCIRG1',
  'Autosomal-recessive osteopetrosis, infantile malignant form (~50% of ARO cases)',
  'pathogenic_for',
  {'evidence': 'TCIRG1-Related Osteopetrosis, GeneReviews; OMIM #259700',
   'mechanism': 'Loss of osteoclast ruffled-border acidification blocks bone resorption'}],
 ['TCIRG1', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['OSTM1',
  'Autosomal-recessive osteopetrosis with primary neurodegeneration (OPTB5), most severe ARO subtype',
  'pathogenic_for',
  {'evidence': 'OSTM1 pleiotropic roles from osteopetrosis to neurodegeneration, 2022; OMIM #259720',
   'mechanism': 'Loss of function destabilizes ClC-7, secondarily disrupting lysosomal/osteoclast '
                'acidification'}],
 ['OSTM1', 'V-ATPase proton-transport pathway', 'part_of_pathway', {}],
 ['Renal-targeted small-molecule V-ATPase corrector', 'ATP6V0A4', 'investigational_for', {}],
 ['Renal-targeted small-molecule V-ATPase corrector', 'ATP6V1B1', 'investigational_for', {}],
 ['TANGO-style splice-switching ASO (zorevunersen-class chemistry)', 'ATP6V0C', 'investigational_for', {}],
 ['Ex vivo lentiviral HSC gene therapy (Zynteglo/Skysona-class modality)',
  'TCIRG1',
  'investigational_for',
  {}]]

HYPOTHESES = [{'candidate_slug': '',
  'gene_symbol': 'ATP6V1A',
  'number': 17,
  'status': 'active',
  'steps': [{'confidence': 0.85,
             'conflicting_evidence': '',
             'experimental_status': 'validated',
             'from_label': 'ATP6V1A loss of function',
             'recommended_next_experiment': 'Confirmatory only - direct functional validation already '
                                            'published.',
             'supporting_papers': [{'title': 'Phenotypic and genetic spectrum of ATP6V1A encephalopathy: a '
                                             'disorder of lysosomal homeostasis',
                                    'url': 'https://ouci.dntb.gov.ua/en/works/4KewMZq9/'},
                                   {'title': 'Clinical and genetic characteristics of DEE93 caused by novel '
                                             'ATP6V1A mutations, Human Mutation 2024',
                                    'url': 'https://onlinelibrary.wiley.com/doi/full/10.1155/2024/4678670'}],
             'to_label': 'decreased lysosomal acidification'},
            {'confidence': 0.75,
             'conflicting_evidence': 'Direct autophagic flux measurement in ATP6V1A patient neurons has not '
                                     'been published as of this research pass; extrapolated from '
                                     'VMA21/lysosomal-storage-disease literature on the same V-ATPase '
                                     'complex.',
             'experimental_status': 'in_progress',
             'from_label': 'decreased lysosomal acidification',
             'recommended_next_experiment': 'LC3-II flux / p62 accumulation assay in ATP6V1A patient-derived '
                                            'iPSC neurons or fibroblasts, +/- bafilomycin challenge.',
             'supporting_papers': [{'title': 'VMA21 deficiency leads to autophagic dysregulation in X-linked '
                                             'myopathy with excessive autophagy, Acta Neuropathologica 2025',
                                    'url': 'https://link.springer.com/article/10.1007/s00401-026-03044-z'}],
             'to_label': 'autophagy failure'},
            {'confidence': 0.5,
             'conflicting_evidence': 'No direct measurement of mTOR activity in ATP6V1A-deficient cells '
                                     'identified in this research pass. This step is a mechanistic '
                                     'hypothesis grounded in general lysosome-mTORC1 signaling biology '
                                     '(Ragulator-Rag GTPase amino-acid sensing occurs on the lysosomal '
                                     'membrane), not disease-specific data.',
             'experimental_status': 'not_started',
             'from_label': 'autophagy failure',
             'recommended_next_experiment': 'Western blot for phospho-S6K1 / phospho-4E-BP1 (mTORC1 activity '
                                            'readout) in ATP6V1A patient cells, +/- rapamycin control.',
             'supporting_papers': [],
             'to_label': 'mTOR dysregulation'},
            {'confidence': 0.45,
             'conflicting_evidence': 'mTOR-synaptic links are established in other epilepsy genes '
                                     '(mTORopathies, e.g. TSC1/TSC2 - tuberous sclerosis) but have not yet '
                                     'been directly demonstrated for ATP6V1A specifically.',
             'experimental_status': 'not_started',
             'from_label': 'mTOR dysregulation',
             'recommended_next_experiment': 'Patch-clamp electrophysiology or synaptic marker imaging '
                                            '(synapsin/PSD-95) in ATP6V1A patient iPSC-derived neurons.',
             'supporting_papers': [],
             'to_label': 'synaptic dysfunction'},
            {'confidence': 0.8,
             'conflicting_evidence': '',
             'experimental_status': 'validated',
             'from_label': 'synaptic dysfunction',
             'recommended_next_experiment': 'n/a - clinical phenotype is directly documented in published '
                                            'cohorts.',
             'supporting_papers': [{'title': 'OMIM #618012 Developmental and Epileptic Encephalopathy 93',
                                    'url': 'https://www.omim.org/entry/618012'}],
             'to_label': 'epileptic encephalopathy (DEE93)'}],
  'title': 'ATP6V1A loss of function drives epileptic encephalopathy via a lysosome-autophagy-mTOR-synapse '
           'cascade'},
 {'candidate_slug': 'atp6v0c',
  'gene_symbol': 'ATP6V0C',
  'number': 18,
  'status': 'active',
  'steps': [{'confidence': 0.7,
             'conflicting_evidence': 'Haploinsufficiency (reduced RNA level) was directly shown in only one '
                                     'reported patient; the mechanism for other variants in the cohort is '
                                     'inferred, not uniformly confirmed.',
             'experimental_status': 'in_progress',
             'from_label': 'ATP6V0C de novo heterozygous variant (haploinsufficiency)',
             'recommended_next_experiment': 'RT-qPCR / allele-specific expression assay across the full '
                                            'reported patient cohort, not just the index case.',
             'supporting_papers': [{'title': 'Novel de novo mutation substantiates ATP6V0C as a gene causing '
                                             'epilepsy with intellectual disability, 2021',
                                    'url': 'https://pubmed.ncbi.nlm.nih.gov/33190975/'}],
             'to_label': 'impaired ATP6V0C-ATP6V0A subunit interaction'},
            {'confidence': 0.65,
             'conflicting_evidence': 'In silico modeling suggested interface disruption; direct biochemical '
                                     'assembly/proton-transport assay in patient cells not yet published.',
             'experimental_status': 'not_started',
             'from_label': 'impaired ATP6V0C-ATP6V0A subunit interaction',
             'recommended_next_experiment': 'Reconstituted V-ATPase assembly assay (co-IP of V0/V1 subunits) '
                                            'and lysosomal pH measurement (LysoSensor) in patient '
                                            'fibroblasts.',
             'supporting_papers': [],
             'to_label': 'reduced V-ATPase assembly / proton transport'},
            {'confidence': 0.75,
             'conflicting_evidence': 'Drosophila knockdown showed increased seizure-like activity and C. '
                                     'elegans patient-variant expression showed motor/lifespan deficits - '
                                     'model-organism evidence, not yet a demonstrated mechanism in human '
                                     'neurons.',
             'experimental_status': 'validated',
             'from_label': 'reduced V-ATPase assembly / proton transport',
             'recommended_next_experiment': 'Patient iPSC-derived neuron seizure-relevant electrophysiology '
                                            '(MEA recording) to bridge the model-organism finding to human '
                                            'cells.',
             'supporting_papers': [{'title': 'Novel de novo mutation substantiates ATP6V0C as a gene causing '
                                             'epilepsy with intellectual disability, 2021',
                                    'url': 'https://pubmed.ncbi.nlm.nih.gov/33190975/'}],
             'to_label': 'neurodevelopmental disorder with epilepsy'}],
  'title': 'ATP6V0C haploinsufficiency impairs V0-V1 assembly, producing a neurodevelopmental disorder with '
           'epilepsy'},
 {'candidate_slug': 'tcirg1',
  'gene_symbol': 'TCIRG1',
  'number': 19,
  'status': 'active',
  'steps': [{'confidence': 0.9,
             'conflicting_evidence': '',
             'experimental_status': 'validated',
             'from_label': 'TCIRG1 loss of function',
             'recommended_next_experiment': 'Confirmatory only - well established across multiple patient '
                                            'cohorts.',
             'supporting_papers': [{'title': 'TCIRG1-Related Osteopetrosis, GeneReviews',
                                    'url': 'https://www.ncbi.nlm.nih.gov/books/NBK617444/'}],
             'to_label': 'loss of osteoclast a3-subunit ruffled-border V-ATPase'},
            {'confidence': 0.85,
             'conflicting_evidence': '',
             'experimental_status': 'validated',
             'from_label': 'loss of osteoclast a3-subunit ruffled-border V-ATPase',
             'recommended_next_experiment': 'n/a for diagnosis; relevant for a future ex vivo potency assay: '
                                            'osteoclast resorption-pit assay on patient-derived, '
                                            'vector-corrected CD34+ cells.',
             'supporting_papers': [{'title': 'TCIRG1-Related Osteopetrosis, GeneReviews',
                                    'url': 'https://www.ncbi.nlm.nih.gov/books/NBK617444/'}],
             'to_label': 'failure of extracellular acidification at the bone-resorption interface'},
            {'confidence': 0.9,
             'conflicting_evidence': '',
             'experimental_status': 'validated',
             'from_label': 'failure of extracellular acidification at the bone-resorption interface',
             'recommended_next_experiment': 'n/a - clinical phenotype directly documented; open question is '
                                            'the gene-therapy potency threshold, see Experiment plan in '
                                            'Layer 5.',
             'supporting_papers': [{'title': 'OMIM #259700 Osteopetrosis, autosomal recessive 1',
                                    'url': 'https://www.omim.org/entry/259700'}],
             'to_label': 'failure of bone resorption -> osteopetrosis, marrow failure, cranial nerve '
                         'compression'}],
  'title': 'TCIRG1 loss of function abolishes osteoclast acidification, causing infantile malignant '
           'osteopetrosis'}]
