"""
Seed data for a fresh database. Sourced from the CADDTARD AI research pass
(V-ATPase LOF gene curation + top-3 candidate prioritization). Re-running
`app.seed.run_seed()` is idempotent - it only inserts if the genes table is empty.
"""

GENES = [{'disease': 'Distal renal tubular acidosis (dRTA), with or without progressive sensorineural hearing loss',
  'in_top3': True,
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Loss of proton translocation; ER retention and proteasomal/lysosomal degradation of missense '
               'variants',
  'omim': 'Gene 602722 · Phenotype 267300 (DRTA2)',
  'organ_system': 'Renal / auditory',
  'protein_name': 'V-type proton ATPase 116 kDa subunit a4',
  'source_citation': 'Molecular mechanisms of cutis laxa- and dRTA-causing mutations in V-ATPase a subunits, '
                     'J Biol Chem 2018',
  'source_url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5827428/',
  'status': 'confirmed',
  'subunit_role': 'V0 a-subunit (kidney/inner-ear isoform)',
  'symbol': 'ATP6V0A4',
  'uniprot_accession': 'Q9HBG4',
  'verification_note': 'xlsx UniProt accession Q9H1X4 does not exist in current UniProt — verified correct '
                       'accession is Q9HBG4.',
  'xlsx_uniprot_claim': 'Q9H1X4'},
 {'disease': 'Cutis laxa type IIA / ARCL2A (wrinkly skin syndrome) with N- and O-glycosylation defects',
  'in_top3': False,
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Golgi pH dysregulation, impaired glycosylation, protein mistrafficking and degradation',
  'omim': 'Gene 611716 · Phenotype 219200 (ARCL2A)',
  'organ_system': 'Dermatologic / connective tissue / Golgi glycosylation',
  'protein_name': 'V-type proton ATPase 116 kDa subunit a2',
  'source_citation': 'A Novel ATP6V0A2 Mutation Causing Recessive Cutis Laxa, Genes 2019',
  'source_url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6373508/',
  'status': 'confirmed',
  'subunit_role': 'V0 a-subunit (Golgi isoform)',
  'symbol': 'ATP6V0A2',
  'uniprot_accession': 'Q9Y487',
  'verification_note': 'xlsx UniProt accession matches verified accession.',
  'xlsx_uniprot_claim': 'Q9Y487'},
 {'disease': 'Distal renal tubular acidosis with early-onset sensorineural hearing loss (DRTA1)',
  'in_top3': True,
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Loss of function; ~70% of patients show early-onset hearing loss vs ~39% for ATP6V0A4',
  'omim': 'Gene 192132 · Phenotype 267300',
  'organ_system': 'Renal / auditory',
  'protein_name': 'V-type proton ATPase subunit B, kidney isoform',
  'source_citation': 'OMIM #267300 DRTA2',
  'source_url': 'https://omim.org/entry/267300',
  'status': 'confirmed',
  'subunit_role': 'V1 B-subunit (kidney isoform)',
  'symbol': 'ATP6V1B1',
  'uniprot_accession': 'P15313',
  'verification_note': 'Not present in uploaded xlsx; added because it is one of the two classic dRTA genes '
                       'and materially changes the renal/auditory cluster size.',
  'xlsx_uniprot_claim': ''},
 {'disease': 'Developmental and epileptic encephalopathy 93 (DEE93); also autosomal-recessive cutis laxa '
             'type IID',
  'in_top3': False,
  'inheritance': 'Autosomal dominant (DEE93, usually de novo) / autosomal recessive (cutis laxa)',
  'mechanism': 'Altered lysosomal homeostasis, abnormal neuritogenesis and synaptic density; both LOF and '
               'GOF variants reported at different residues',
  'omim': 'Gene 607027 · Phenotype 618012 (DEE93)',
  'organ_system': 'Neurodevelopmental / epilepsy; also dermatologic-connective tissue',
  'protein_name': 'V-type proton ATPase catalytic subunit A',
  'source_citation': 'Clinical and genetic characteristics of DEE93, Human Mutation 2024',
  'source_url': 'https://onlinelibrary.wiley.com/doi/full/10.1155/2024/4678670',
  'status': 'confirmed',
  'subunit_role': 'V1 A-subunit (catalytic, ATP hydrolysis)',
  'symbol': 'ATP6V1A',
  'uniprot_accession': 'P38606',
  'verification_note': "xlsx UniProt accession matches; xlsx disease label 'developmental delay' is "
                       'directionally correct but should be refined to DEE93 / epilepsy for clinical use.',
  'xlsx_uniprot_claim': 'P38606'},
 {'disease': 'Autosomal-recessive cutis laxa type IIC (ARCL2C)',
  'in_top3': False,
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Loss of function destabilizes V1 peripheral stalk assembly',
  'omim': 'Gene 609150',
  'organ_system': 'Dermatologic / connective tissue',
  'protein_name': 'V-type proton ATPase subunit E1',
  'source_citation': 'Mutations in ATP6V1E1 or ATP6V1A Cause Autosomal-Recessive Cutis Laxa, AJHG 2020',
  'source_url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7413885/',
  'status': 'confirmed',
  'subunit_role': 'V1 E-subunit (peripheral stalk / regulatory)',
  'symbol': 'ATP6V1E1',
  'uniprot_accession': 'P36543',
  'verification_note': "xlsx UniProt accession matches; xlsx disease label 'developmental delay' should be "
                       'corrected to cutis laxa type IIC per primary literature.',
  'xlsx_uniprot_claim': 'P36543'},
 {'disease': 'Neurodevelopmental disorder with or without epilepsy (de novo heterozygous variants; '
             'haploinsufficiency in at least one reported case)',
  'in_top3': True,
  'inheritance': 'Autosomal dominant (de novo)',
  'mechanism': 'Impaired ATP6V0C-ATP6V0A subunit interaction; reduced RNA level in at least one patient '
               'consistent with haploinsufficiency',
  'omim': 'No stable phenotype MIM as of literature reviewed (2020-2021 cohort)',
  'organ_system': 'Neurodevelopmental / epilepsy',
  'protein_name': 'V-type proton ATPase 16 kDa proteolipid subunit c',
  'source_citation': 'Novel de novo mutation substantiates ATP6V0C as a gene causing epilepsy with '
                     'intellectual disability, 2021',
  'source_url': 'https://pubmed.ncbi.nlm.nih.gov/33190975/',
  'status': 'confirmed',
  'subunit_role': 'V0 c-subunit (proteolipid ring; bafilomycin binding site)',
  'symbol': 'ATP6V0C',
  'uniprot_accession': 'P27449',
  'verification_note': 'xlsx UniProt accession matches; xlsx used this gene for its '
                       'neurodevelopmental-phenotype rows, consistent with the literature association.',
  'xlsx_uniprot_claim': 'P27449'},
 {'disease': 'No confirmed monogenic human disease association identified in this research pass',
  'in_top3': False,
  'inheritance': 'Not established',
  'mechanism': 'Studied mainly in osteoclast bone resorption and as a cancer-context gene; not established '
               'as a Mendelian LOF-disease gene',
  'omim': 'n/a',
  'organ_system': 'Candidate: skeletal / osteoclast biology',
  'protein_name': 'V-type proton ATPase subunit d1',
  'source_citation': 'Not found — recommend direct ClinVar/OMIM query before use',
  'source_url': '',
  'status': 'unverified',
  'subunit_role': 'V0 d-subunit (rotor)',
  'symbol': 'ATP6V0D1',
  'uniprot_accession': 'P61421',
  'verification_note': 'xlsx UniProt accession is real (matches ATP6V0D1) but the 12 rows labeled '
                       "'neurodevelopmental phenotype' for this gene could not be corroborated against "
                       'OMIM/ClinVar/primary literature in this pass. Treat as a hypothesis-generating '
                       'placeholder pending curation.',
  'xlsx_uniprot_claim': 'P61421'},
 {'disease': 'No confirmed monogenic human disease association identified in this research pass',
  'in_top3': False,
  'inheritance': 'Not established',
  'mechanism': 'n/a',
  'omim': 'n/a',
  'organ_system': 'Not established',
  'protein_name': 'V-type proton ATPase subunit G1',
  'source_citation': 'Not found — recommend direct ClinVar/OMIM query before use',
  'source_url': '',
  'status': 'unverified',
  'subunit_role': 'V1 G-subunit (peripheral stalk)',
  'symbol': 'ATP6V1G1',
  'uniprot_accession': 'O75348',
  'verification_note': 'xlsx UniProt accession is real (matches ATP6V1G1) but the disease label '
                       "'neurodevelopmental delay' could not be corroborated in this pass.",
  'xlsx_uniprot_claim': 'O75348'},
 {'disease': 'X-linked myopathy with excessive autophagy (XMEA); VMA21-congenital disorder of glycosylation',
  'in_top3': False,
  'inheritance': 'X-linked recessive',
  'mechanism': 'Reduced V-ATPase assembly efficiency lowers lysosomal V-ATPase content, raising lysosomal pH '
               'and partially blocking macroautophagy, causing vacuolation',
  'omim': 'Phenotype 310440 (MEAX)',
  'organ_system': 'Musculoskeletal (myopathy)',
  'protein_name': 'Vacuolar ATPase assembly integral membrane protein VMA21',
  'source_citation': 'VMA21 deficiency leads to autophagic dysregulation in XMEA, Acta Neuropathologica '
                     '2025; OMIM #310440',
  'source_url': 'https://link.springer.com/article/10.1007/s00401-026-03044-z',
  'status': 'confirmed',
  'subunit_role': 'V0 assembly chaperone (ER-resident, not part of mature holoenzyme)',
  'symbol': 'VMA21',
  'uniprot_accession': 'Q3ZAQ7',
  'verification_note': 'Not present in uploaded xlsx. This is the principal muscle-phenotype gene in the '
                       "pathway and should be added to any dataset intended to cover 'muscular' LOF effects.",
  'xlsx_uniprot_claim': ''},
 {'disease': 'Immunodeficiency 47 with hepatopathy (IMD47); ATP6AP1-congenital disorder of glycosylation '
             '(type IIs)',
  'in_top3': False,
  'inheritance': 'X-linked recessive',
  'mechanism': 'Loss of function impairs V0 assembly and N-glycosylation of secreted/membrane proteins',
  'omim': 'Gene 300197 · Phenotype 300972 (IMD47)',
  'organ_system': 'Immunologic / hepatic / glycosylation',
  'protein_name': 'V-type proton ATPase subunit S1 (Ac45)',
  'source_citation': 'ATP6AP1 deficiency causes an immunodeficiency with hepatopathy, Nat Commun 2016; OMIM '
                     '#300972',
  'source_url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4894975/',
  'status': 'confirmed',
  'subunit_role': 'Accessory subunit; V0 assembly hub',
  'symbol': 'ATP6AP1',
  'uniprot_accession': 'Q15904',
  'verification_note': 'Not present in uploaded xlsx.',
  'xlsx_uniprot_claim': ''},
 {'disease': 'X-linked parkinsonism with spasticity (XPDS); ATP6AP2-congenital disorder of glycosylation '
             'with liver disease, immunodeficiency and cutis laxa',
  'in_top3': False,
  'inheritance': 'X-linked',
  'mechanism': 'Hypomorphic missense variants cause tissue-specific hypoglycosylation and autophagy defects; '
               'more severe truncating variants cause the glycosylation/liver/immune syndrome',
  'omim': 'Gene 300556 · Phenotype 300911 (XPDS)',
  'organ_system': 'Neurologic (parkinsonism) / immunologic-hepatic / dermatologic',
  'protein_name': 'Renin receptor / ATPase H+-transporting accessory protein 2',
  'source_citation': 'Mutations in the X-linked ATP6AP2 cause a glycosylation disorder with autophagic '
                     'defects, J Exp Med 2017; OMIM #300911',
  'source_url': 'https://omim.org/entry/300911',
  'status': 'confirmed',
  'subunit_role': 'Accessory subunit (also the (pro)renin receptor)',
  'symbol': 'ATP6AP2',
  'uniprot_accession': 'O75787',
  'verification_note': 'Not present in uploaded xlsx.',
  'xlsx_uniprot_claim': ''},
 {'disease': 'Autosomal-recessive osteopetrosis, infantile malignant form (~50% of ARO cases)',
  'in_top3': True,
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Loss of osteoclast ruffled-border acidification blocks bone resorption',
  'omim': 'Gene 604592 · Phenotype 259700 (OPTB1)',
  'organ_system': 'Skeletal (osteoclast) / hematologic / can include CNS involvement',
  'protein_name': 'V-type proton ATPase 116 kDa subunit a3',
  'source_citation': 'TCIRG1-Related Osteopetrosis, GeneReviews; OMIM #259700',
  'source_url': 'https://www.ncbi.nlm.nih.gov/books/NBK617444/',
  'status': 'confirmed',
  'subunit_role': 'V0 a-subunit (osteoclast isoform)',
  'symbol': 'TCIRG1',
  'uniprot_accession': 'Q13488',
  'verification_note': 'Not present in uploaded xlsx.',
  'xlsx_uniprot_claim': ''},
 {'disease': 'Autosomal-recessive osteopetrosis with primary neurodegeneration (OPTB5), most severe ARO '
             'subtype',
  'in_top3': False,
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Loss of function destabilizes ClC-7, secondarily disrupting lysosomal/osteoclast '
               'acidification',
  'omim': 'Gene 607649 · Phenotype 259720 (OPTB5)',
  'organ_system': 'Skeletal + neurodegeneration',
  'protein_name': 'Osteopetrosis-associated transmembrane protein 1 (chloride channel 7 beta subunit)',
  'source_citation': 'OSTM1 pleiotropic roles from osteopetrosis to neurodegeneration, 2022; OMIM #259720',
  'source_url': 'https://pubmed.ncbi.nlm.nih.gov/35902071/',
  'status': 'confirmed',
  'subunit_role': 'Lysosomal/osteoclast acidification accessory factor (ClC-7 beta subunit, functionally '
                  'coupled to V-ATPase-driven acidification)',
  'symbol': 'OSTM1',
  'uniprot_accession': 'Q86WC4',
  'verification_note': 'Not present in uploaded xlsx. Not a V-ATPase subunit itself but functionally coupled '
                       'to the same acidification pathway and commonly grouped with V-ATPase LOF disease in '
                       'the literature.',
  'xlsx_uniprot_claim': ''}]

VARIANTS = [{'confidence': 0.55,
  'conservation_score': 0.89,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R40W',
  'phenotype_severity': 'severe',
  'position': 40,
  'predicted_delta_g': -3.281,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G77D',
  'phenotype_severity': 'moderate',
  'position': 77,
  'predicted_delta_g': -2.997,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L151P',
  'phenotype_severity': 'severe',
  'position': 151,
  'predicted_delta_g': -3.447,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.94,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R410W',
  'phenotype_severity': 'moderate',
  'position': 410,
  'predicted_delta_g': -3.266,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.92,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L521P',
  'phenotype_severity': 'moderate',
  'position': 521,
  'predicted_delta_g': -3.305,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.88,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I558T',
  'phenotype_severity': 'mild',
  'position': 558,
  'predicted_delta_g': -3.165,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.91,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R260W',
  'phenotype_severity': 'mild',
  'position': 260,
  'predicted_delta_g': -3.145,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.95,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G297D',
  'phenotype_severity': 'severe',
  'position': 297,
  'predicted_delta_g': -3.176,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.96,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L371P',
  'phenotype_severity': 'mild',
  'position': 371,
  'predicted_delta_g': -3.183,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.8,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I408T',
  'phenotype_severity': 'severe',
  'position': 408,
  'predicted_delta_g': -3.059,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.82,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1E1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'S',
  'mutation': 'F556S',
  'phenotype_severity': 'moderate',
  'position': 556,
  'predicted_delta_g': -2.767,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'F'},
 {'confidence': 0.55,
  'conservation_score': 0.95,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R110W',
  'phenotype_severity': 'severe',
  'position': 110,
  'predicted_delta_g': -3.023,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G147D',
  'phenotype_severity': 'moderate',
  'position': 147,
  'predicted_delta_g': -3.147,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.76,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L221P',
  'phenotype_severity': 'severe',
  'position': 221,
  'predicted_delta_g': -2.843,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'loop',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.77,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I258T',
  'phenotype_severity': 'moderate',
  'position': 258,
  'predicted_delta_g': -2.938,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.91,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1E1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'S',
  'mutation': 'F406S',
  'phenotype_severity': 'mild',
  'position': 406,
  'predicted_delta_g': -2.78,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'F'},
 {'confidence': 0.55,
  'conservation_score': 0.88,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R480W',
  'phenotype_severity': 'moderate',
  'position': 480,
  'predicted_delta_g': -2.774,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'loop',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.8,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G517D',
  'phenotype_severity': 'mild',
  'position': 517,
  'predicted_delta_g': -2.921,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0C',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'K',
  'mutation': 'E554K',
  'phenotype_severity': 'severe',
  'position': 554,
  'predicted_delta_g': -2.753,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'E'},
 {'confidence': 0.55,
  'conservation_score': 0.97,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L71P',
  'phenotype_severity': 'moderate',
  'position': 71,
  'predicted_delta_g': -3.29,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.81,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I108T',
  'phenotype_severity': 'mild',
  'position': 108,
  'predicted_delta_g': -2.816,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.92,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1G1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'C',
  'mutation': 'Y293C',
  'phenotype_severity': 'moderate',
  'position': 293,
  'predicted_delta_g': -2.864,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'Y'},
 {'confidence': 0.55,
  'conservation_score': 0.92,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R330W',
  'phenotype_severity': 'mild',
  'position': 330,
  'predicted_delta_g': -3.102,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G367D',
  'phenotype_severity': 'severe',
  'position': 367,
  'predicted_delta_g': -2.897,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.9,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L441P',
  'phenotype_severity': 'mild',
  'position': 441,
  'predicted_delta_g': -2.791,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'surface',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.84,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1G1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'C',
  'mutation': 'Y143C',
  'phenotype_severity': 'mild',
  'position': 143,
  'predicted_delta_g': -2.758,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'Y'},
 {'confidence': 0.55,
  'conservation_score': 0.94,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L291P',
  'phenotype_severity': 'severe',
  'position': 291,
  'predicted_delta_g': -3.469,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.95,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I328T',
  'phenotype_severity': 'moderate',
  'position': 328,
  'predicted_delta_g': -3.014,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.89,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R550W',
  'phenotype_severity': 'moderate',
  'position': 550,
  'predicted_delta_g': -3.281,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G67D',
  'phenotype_severity': 'mild',
  'position': 67,
  'predicted_delta_g': -2.997,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L141P',
  'phenotype_severity': 'moderate',
  'position': 141,
  'predicted_delta_g': -3.447,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R400W',
  'phenotype_severity': 'mild',
  'position': 400,
  'predicted_delta_g': -3.294,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.79,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L511P',
  'phenotype_severity': 'mild',
  'position': 511,
  'predicted_delta_g': -3.214,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.92,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I548T',
  'phenotype_severity': 'severe',
  'position': 548,
  'predicted_delta_g': -3.193,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.78,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R250W',
  'phenotype_severity': 'severe',
  'position': 250,
  'predicted_delta_g': -3.054,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G287D',
  'phenotype_severity': 'moderate',
  'position': 287,
  'predicted_delta_g': -3.197,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L361P',
  'phenotype_severity': 'severe',
  'position': 361,
  'predicted_delta_g': -3.197,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.84,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I398T',
  'phenotype_severity': 'moderate',
  'position': 398,
  'predicted_delta_g': -3.087,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.86,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1E1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'S',
  'mutation': 'F546S',
  'phenotype_severity': 'mild',
  'position': 546,
  'predicted_delta_g': -2.795,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'F'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R100W',
  'phenotype_severity': 'moderate',
  'position': 100,
  'predicted_delta_g': -3.044,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.91,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G137D',
  'phenotype_severity': 'mild',
  'position': 137,
  'predicted_delta_g': -3.098,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.8,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L211P',
  'phenotype_severity': 'moderate',
  'position': 211,
  'predicted_delta_g': -2.871,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'loop',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.81,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I248T',
  'phenotype_severity': 'mild',
  'position': 248,
  'predicted_delta_g': -2.966,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.95,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1E1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'S',
  'mutation': 'F396S',
  'phenotype_severity': 'severe',
  'position': 396,
  'predicted_delta_g': -2.808,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'F'},
 {'confidence': 0.55,
  'conservation_score': 0.92,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R470W',
  'phenotype_severity': 'mild',
  'position': 470,
  'predicted_delta_g': -2.802,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'loop',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.84,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G507D',
  'phenotype_severity': 'severe',
  'position': 507,
  'predicted_delta_g': -2.95,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L61P',
  'phenotype_severity': 'mild',
  'position': 61,
  'predicted_delta_g': -3.297,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.85,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I98T',
  'phenotype_severity': 'severe',
  'position': 98,
  'predicted_delta_g': -2.844,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.96,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1G1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'C',
  'mutation': 'Y283C',
  'phenotype_severity': 'mild',
  'position': 283,
  'predicted_delta_g': -2.892,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'Y'},
 {'confidence': 0.55,
  'conservation_score': 0.96,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R320W',
  'phenotype_severity': 'severe',
  'position': 320,
  'predicted_delta_g': -3.13,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.88,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G357D',
  'phenotype_severity': 'moderate',
  'position': 357,
  'predicted_delta_g': -2.828,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'active_site',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.88,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1G1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'C',
  'mutation': 'Y133C',
  'phenotype_severity': 'severe',
  'position': 133,
  'predicted_delta_g': -2.786,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'Y'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L281P',
  'phenotype_severity': 'moderate',
  'position': 281,
  'predicted_delta_g': -3.497,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.82,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I318T',
  'phenotype_severity': 'mild',
  'position': 318,
  'predicted_delta_g': -2.923,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'I'},
 {'confidence': 0.55,
  'conservation_score': 0.93,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R540W',
  'phenotype_severity': 'mild',
  'position': 540,
  'predicted_delta_g': -3.309,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.89,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A2',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'D',
  'mutation': 'G57D',
  'phenotype_severity': 'severe',
  'position': 57,
  'predicted_delta_g': -2.934,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'interface',
  'wt_aa': 'G'},
 {'confidence': 0.55,
  'conservation_score': 0.9,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L131P',
  'phenotype_severity': 'mild',
  'position': 131,
  'predicted_delta_g': -3.391,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.98,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0A4',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'W',
  'mutation': 'R390W',
  'phenotype_severity': 'severe',
  'position': 390,
  'predicted_delta_g': -3.294,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'core',
  'wt_aa': 'R'},
 {'confidence': 0.55,
  'conservation_score': 0.83,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V0D1',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'P',
  'mutation': 'L501P',
  'phenotype_severity': 'severe',
  'position': 501,
  'predicted_delta_g': -3.242,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane',
  'wt_aa': 'L'},
 {'confidence': 0.55,
  'conservation_score': 0.96,
  'degradation_risk': 'high',
  'gene_symbol': 'ATP6V1A',
  'mechanism_class': 'LOF_degradation_driven',
  'mut_aa': 'T',
  'mutation': 'I538T',
  'phenotype_severity': 'moderate',
  'position': 538,
  'predicted_delta_g': -3.221,
  'source': 'synthetic_starter_replace_with_ClinVar_UniProt_literature',
  'structural_region': 'membrane_core',
  'wt_aa': 'I'}]

SCORING = [{'cmc': 4,
  'commercial': 3,
  'composite': 3.75,
  'feasibility': 4,
  'genes': 'ATP6V0A4, ATP6V1B1',
  'patients': 4,
  'program': 'Distal renal tubular acidosis (ATP6V0A4 + ATP6V1B1)',
  'rationale': 'Largest diagnosed/published patient base of the set (multiple multi-country cohorts: Spain, '
               'China, Tunisia, Malaysia, others). Kidney-accessible tissue supports oral small-molecule or '
               'systemic ASO delivery. Established, cheap biomarkers (urine pH, serum bicarbonate, anion '
               'gap) enable fast, objective proof-of-concept trials. Commercial ceiling is capped by '
               'existing oral alkali standard of care, but alkali does not fully prevent nephrocalcinosis, '
               'growth failure, or progressive CKD, leaving real unmet need.',
  'selected': True},
 {'cmc': 3,
  'commercial': 5,
  'composite': 3.75,
  'feasibility': 4,
  'genes': 'ATP6V0C',
  'patients': 3,
  'program': 'Neurodevelopmental disorder with epilepsy (ATP6V0C)',
  'rationale': 'Haploinsufficiency mechanism (de novo heterozygous LOF, RNA level ~50% of normal in at least '
               'one reported case) is the ideal substrate for splice-switching ASO augmentation - directly '
               "analogous to Stoke Therapeutics' TANGO platform and its lead asset zorevunersen (STK-001) "
               'for SCN1A-haploinsufficient Dravet syndrome, now partnered with Biogen and in Phase 3 '
               '(EMPEROR study). This is the strongest direct commercial/regulatory precedent in the entire '
               'gene set. CNS (intrathecal) delivery is required, which raises CMC/administration complexity '
               'but is itself precedented (nusinersen, zorevunersen). Diagnosed cohort is growing quickly as '
               'exome/genome sequencing expands (27 patients in the founding 2020-21 cohort alone).',
  'selected': True},
 {'cmc': 4,
  'commercial': 3,
  'composite': 3.25,
  'feasibility': 3,
  'genes': 'TCIRG1',
  'patients': 3,
  'program': 'Infantile malignant osteopetrosis (TCIRG1)',
  'rationale': 'TCIRG1 causes ~50% of autosomal recessive osteopetrosis (ARO), and ARO has a real, citable '
               'birth incidence of about 1 in 250,000 - the only candidate in the set with a hard '
               'population-level epidemiological anchor rather than a small case-series count. Ex vivo '
               'lentiviral hematopoietic stem cell gene therapy is an FDA-approved modality class (Zynteglo '
               'for beta-thalassemia, Skysona for cerebral adrenoleukodystrophy), giving TCIRG1 the '
               'strongest regulatory and manufacturing precedent of any candidate. Major caveat: allogeneic '
               'HSCT is already curative for most HSCT-eligible ARO patients if performed early, which '
               'narrows the differentiated commercial opportunity to HSCT-ineligible or high-risk patients, '
               'and the lentiviral modality class carries a documented insertional-mutagenesis/leukemia '
               'signal (10 of 67 Skysona trial participants developed hematologic malignancy as of a July '
               '2025 safety update) that must be addressed head-on in any non-clinical safety package.',
  'selected': True},
 {'cmc': 3,
  'commercial': 3,
  'composite': 2.75,
  'feasibility': 4,
  'genes': 'VMA21',
  'patients': 1,
  'program': 'X-linked myopathy with excessive autophagy (VMA21)',
  'rationale': 'Close #4. Best feasibility profile in the set - slowly progressive (not rapidly fatal), a '
               '2024 published natural history study already exists, and muscle-directed AAV capsids are a '
               'mature manufacturing platform. No competing program was identified (genuine white space). '
               'But it has the smallest population of any candidate reviewed - approximately 24-45 '
               'genetically confirmed patients described worldwide across the literature - which is a '
               'serious constraint under a conventional commercial-return model, though it remains viable '
               'under a foundation-funded / individualized-therapy model (comparable to CureSPG50 or similar '
               'ultra-rare AAV programs).',
  'selected': False},
 {'cmc': 3,
  'commercial': 3,
  'composite': 2.375,
  'feasibility': 1.5,
  'genes': 'ATP6V1A',
  'patients': 2,
  'program': 'Developmental and epileptic encephalopathy 93 (ATP6V1A)',
  'rationale': 'Epilepsy is a large commercial category and CNS ASO delivery is precedented, but ATP6V1A '
               'pathogenic variants have been shown to act through both loss-of-function and '
               'gain-of-function mechanisms at different residues in the same gene. A single therapeutic '
               'hypothesis (e.g., augmentation) is not safely generalizable across the patient population '
               'without variant-level stratification, which fragments an already-small cohort and materially '
               'raises program risk.',
  'selected': False},
 {'cmc': 2,
  'commercial': 2,
  'composite': 2.0,
  'feasibility': 2,
  'genes': 'ATP6V0A2',
  'patients': 2,
  'program': 'Cutis laxa type IIA (ATP6V0A2)',
  'rationale': 'Multisystem congenital connective-tissue and glycosylation disorder; substantial structural '
               'damage (skin, skeletal, sometimes CNS) may occur prenatally/early in development, limiting '
               'the benefit of a postnatal correction. Small reported population.',
  'selected': False},
 {'cmc': 2,
  'commercial': 2,
  'composite': 2.0,
  'feasibility': 2,
  'genes': 'ATP6V1E1',
  'patients': 2,
  'program': 'Cutis laxa type IIC (ATP6V1E1)',
  'rationale': 'Same connective-tissue/timing-of-damage limitation as ATP6V0A2, smaller reported population.',
  'selected': False},
 {'cmc': 2,
  'commercial': 2,
  'composite': 1.75,
  'feasibility': 2,
  'genes': 'ATP6AP1',
  'patients': 1,
  'program': 'Immunodeficiency 47 with hepatopathy (ATP6AP1)',
  'rationale': 'Only a handful of families reported; systemic glycosylation defect is mechanistically harder '
               'to correct with a single modality.',
  'selected': False},
 {'cmc': 2,
  'commercial': 2,
  'composite': 1.75,
  'feasibility': 2,
  'genes': 'ATP6AP2',
  'patients': 1,
  'program': 'X-linked parkinsonism with spasticity (ATP6AP2)',
  'rationale': 'Originally described in essentially one large multigenerational family; population too small '
               'to support a standard program at this time.',
  'selected': False},
 {'cmc': 2,
  'commercial': 2,
  'composite': 1.75,
  'feasibility': 2,
  'genes': 'OSTM1',
  'patients': 1,
  'program': 'Osteopetrosis with neurodegeneration (OSTM1)',
  'rationale': 'Most severe ARO subtype (~5% of ARO cases) with early infantile mortality; narrow treatment '
               'window and dual bone+CNS targeting requirement make this the highest-difficulty, '
               'smallest-population candidate reviewed.',
  'selected': False}]

CANDIDATES = [{'biomarkers': 'Urine pH, blood/urine anion gap, serum bicarbonate, urinary citrate, renal ultrasound '
                '(nephrocalcinosis) - all standard, cheap, and already used in clinical dRTA diagnosis and '
                'monitoring, which shortens and de-risks trial design.',
  'commercial_precedent': 'No direct approved precedent for genetic dRTA specifically, but the '
                          'CFTR-corrector playbook (small molecule chaperones correcting a misfolded, '
                          'trafficking-defective membrane transporter) is a validated template from cystic '
                          'fibrosis; renal rare-disease programs (e.g., in other transporter/channel '
                          'disorders) have precedent for orphan approval on biomarker-based endpoints.',
  'genes': 'ATP6V0A4 + ATP6V1B1',
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Loss of apical proton secretion by alpha-intercalated cells of the distal nephron; ATP6V0A4 '
               'variants are also ER-retained/degraded, ATP6V1B1 loss additionally affects '
               'cochlear/endolymphatic acidification producing early hearing loss in ~70% of ATP6V1B1 '
               'patients vs ~39% of ATP6V0A4 patients.',
  'modality': 'Lead option: kidney-selective small molecule (proteostasis corrector / chaperone for '
              'misfolded a4 or B1 subunit, analogous to CFTR correctors in cystic fibrosis) or an mRNA/ASO '
              'approach if haploinsufficiency-type variants are prioritized. Renal-targeted delivery reduces '
              'systemic exposure risk.',
  'name': 'Distal renal tubular acidosis',
  'omim': 'Gene 602722 / 192132 - Phenotype 267300 (DRTA2)',
  'organ': 'Renal / auditory',
  'risks': 'Standard-of-care ceiling: alkali therapy is inexpensive, generic and already reasonably '
           'effective for the acid-base component specifically, which will pressure pricing/reimbursement '
           'unless the new therapy demonstrates superiority on hard renal outcomes (nephrocalcinosis, CKD '
           'progression, growth) rather than acid-base labs alone.',
  'slug': 'drta',
  'soc': 'Chronic oral alkali (potassium citrate/bicarbonate) plus potassium and vitamin D/electrolyte '
         'management. Effective at correcting systemic acidosis but adherence-dependent, does not reliably '
         'prevent nephrocalcinosis, nephrolithiasis, growth failure, or progressive CKD in many patients.',
  'uniprot': 'Q9HBG4 (ATP6V0A4) / P15313 (ATP6V1B1)'},
 {'biomarkers': 'EEG seizure frequency/severity, standardized developmental assessments (Bayley/Vineland), '
                'patient-derived iPSC-neuron ATP6V0C RNA and lysosomal pH as a translatable pharmacodynamic '
                'biomarker for target engagement.',
  'commercial_precedent': 'Direct, current, large-cap-partnered precedent: Stoke Therapeutics (Nasdaq: STOK) '
                          '/ Biogen zorevunersen program for Dravet syndrome validates both the TANGO '
                          'chemistry platform and the haploinsufficiency-ASO commercial thesis in the same '
                          'CNS/pediatric-epilepsy category.',
  'genes': 'ATP6V0C',
  'inheritance': 'Autosomal dominant (de novo)',
  'mechanism': 'De novo heterozygous variants impair the ATP6V0C-ATP6V0A subunit interface within the V0 '
               'proteolipid ring; at least one patient showed ATP6V0C RNA at roughly half the level of '
               'unaffected parents, consistent with haploinsufficiency as (at least) one disease mechanism.',
  'modality': 'Lead option: splice-switching / TANGO-style antisense oligonucleotide designed to upregulate '
              'expression from the remaining wild-type ATP6V0C allele, directly modeled on Stoke '
              "Therapeutics' approach for SCN1A-haploinsufficient Dravet syndrome (zorevunersen/STK-001, "
              'Phase 3 with Biogen).',
  'name': 'ATP6V0C neurodevelopmental disorder with epilepsy',
  'omim': 'Gene not yet assigned a stable phenotype MIM as of the literature reviewed (2020-2021 founding '
          'cohort, 27 patients)',
  'organ': 'Neurodevelopmental / epilepsy',
  'risks': 'Intrathecal CNS delivery adds cost and administration burden versus a systemic therapy. '
           'Diagnosed population is still small (dozens reported) though expected to grow with expanded '
           'genetic testing; a natural history study should run in parallel with IND-enabling work to '
           'support trial design and regulatory engagement.',
  'slug': 'atp6v0c',
  'soc': 'Standard anti-seizure medications only (symptomatic); no disease-modifying therapy exists.',
  'uniprot': 'P27449'},
 {'biomarkers': 'Bone density/skeletal imaging, hematologic parameters (cytopenias from marrow space '
                'compromise), growth parameters, vision/hearing screening (cranial nerve compression) - all '
                'standard, well-described in the osteopetrosis natural history literature.',
  'commercial_precedent': 'Ex vivo lentiviral HSC gene therapy is an approved, reimbursed modality class '
                          'with two precedents (Zynteglo, Skysona), giving TCIRG1 the strongest '
                          'regulatory/manufacturing pathway precedent of the three candidates.',
  'genes': 'TCIRG1',
  'inheritance': 'Autosomal recessive',
  'mechanism': 'Loss of the osteoclast-specific V-ATPase a3 subunit abolishes ruffled-border acidification, '
               'blocking bone resorption; causes ~50% of autosomal recessive osteopetrosis, which has a '
               'citable birth incidence of about 1 in 250,000.',
  'modality': 'Lead option: autologous ex vivo lentiviral-corrected HSC gene therapy, the same modality '
              'class as FDA-approved Zynteglo (beta-thalassemia) and Skysona (cerebral adrenoleukodystrophy) '
              '- positioned specifically for HSCT-ineligible patients (no matched donor) or as an '
              'alternative to allogeneic transplant risk (graft-vs-host disease).',
  'name': 'Infantile malignant osteopetrosis (ARO1)',
  'omim': 'Gene 604592 - Phenotype 259700 (OPTB1)',
  'organ': 'Skeletal (osteoclast) / hematologic, can include CNS',
  'risks': 'Two major, well-documented risks must be addressed head-on: (1) competition with curative '
           'allogeneic HSCT for the majority of eligible patients narrows the addressable population to '
           'HSCT-ineligible/high-risk cases; (2) lentiviral insertional mutagenesis carries a real leukemia '
           'signal - 10 of 67 Skysona trial participants (15%) had developed hematologic malignancy as of a '
           'July 2025 safety update - and this must be a central focus of the non-clinical '
           'genotoxicity/integration-site package.',
  'slug': 'tcirg1',
  'soc': 'Allogeneic hematopoietic stem cell transplant (HSCT) is curative for the bone/marrow phenotype in '
         'most HSCT-eligible patients if performed early; patients without an HLA-matched donor, or '
         'diagnosed late, have limited options and high morbidity/mortality.',
  'uniprot': 'Q13488'}]

TIMELINE = {'atp6v0c': [{'detail': 'Design and select lead ASO sequence using TANGO-style splice-switching approach; '
                        'confirm CNS/intrathecal delivery plan; pre-IND / INTERACT meeting.',
              'month_label': 'M1-M2',
              'sort_order': 0,
              'track': 'Candidate lock'},
             {'detail': 'Target engagement and RNA/protein rescue in patient iPSC-neurons; confirm lysosomal '
                        'pH normalization as PD biomarker.',
              'month_label': 'M2-M5',
              'sort_order': 1,
              'track': 'Non-clinical pharmacology'},
             {'detail': 'GMP oligonucleotide synthesis; analytical method validation; stability program.',
              'month_label': 'M3-M7',
              'sort_order': 2,
              'track': 'CMC'},
             {'detail': 'GLP intrathecal-route repeat-dose tox in NHP or large-animal model; CNS safety '
                        'pharmacology; genotoxicity.',
              'month_label': 'M4-M9',
              'sort_order': 3,
              'track': 'GLP toxicology'},
             {'detail': 'Nonclinical overview; natural history study initiation in parallel; orphan/rare '
                        'pediatric disease designation.',
              'month_label': 'M6-M9',
              'sort_order': 4,
              'track': 'Regulatory package'},
             {'detail': 'Submit IND; respond to FDA queries.',
              'month_label': 'M9-M11',
              'sort_order': 5,
              'track': 'IND submission'},
             {'detail': 'Site activation; first-patient dosing.',
              'month_label': 'M11-M12',
              'sort_order': 6,
              'track': 'Clinical readiness'}],
 'drta': [{'detail': 'Finalize lead small-molecule corrector (or select repurposed CFTR-corrector-class '
                     'asset for rapid re-profiling); confirm dRTA patient registry / natural history '
                     'partner; pre-IND meeting request.',
           'month_label': 'M1-M2',
           'sort_order': 0,
           'track': 'Candidate lock'},
          {'detail': 'Rescue of trafficking/proton-transport defect in patient-derived cells and a4/B1 '
                     'knock-in models; dose range-finding.',
           'month_label': 'M2-M5',
           'sort_order': 1,
           'track': 'Non-clinical pharmacology'},
          {'detail': 'GMP synthesis of oral drug substance/product; stability program.',
           'month_label': 'M3-M7',
           'sort_order': 2,
           'track': 'CMC'},
          {'detail': 'GLP repeat-dose rat + dog tox, safety pharmacology, genotoxicity.',
           'month_label': 'M4-M8',
           'sort_order': 3,
           'track': 'GLP toxicology'},
          {'detail': 'Nonclinical overview, orphan drug designation filing, biomarker qualification package '
                     '(urine pH/anion gap as endpoints).',
           'month_label': 'M6-M9',
           'sort_order': 4,
           'track': 'Regulatory package'},
          {'detail': 'Submit IND; respond to FDA queries.',
           'month_label': 'M9-M11',
           'sort_order': 5,
           'track': 'IND submission'},
          {'detail': 'Site activation; first-patient dosing.',
           'month_label': 'M11-M12',
           'sort_order': 6,
           'track': 'Clinical readiness'}],
 'tcirg1': [{'detail': 'Finalize lentiviral vector design (TCIRG1 cDNA construct); confirm eligibility '
                       'criteria (HSCT-ineligible/no matched donor); pre-IND meeting.',
             'month_label': 'M1-M2',
             'sort_order': 0,
             'track': 'Candidate lock'},
            {'detail': 'Transduction efficiency and osteoclast functional rescue in patient CD34+ cells and '
                       'Tcirg1-deficient (oc/oc) mouse model.',
             'month_label': 'M2-M6',
             'sort_order': 1,
             'track': 'Non-clinical pharmacology'},
            {'detail': 'GMP lentiviral vector manufacture; closed-system CD34+ cell processing development; '
                       'potency assay development and validation.',
             'month_label': 'M3-M9',
             'sort_order': 2,
             'track': 'CMC'},
            {'detail': 'Conditioning-regimen tox; integration-site analysis and long-term genotoxicity '
                       'follow-up in a large-animal or humanized-mouse model, directly addressing the '
                       'lentiviral insertional-mutagenesis signal seen with Skysona.',
             'month_label': 'M5-M11',
             'sort_order': 3,
             'track': 'GLP toxicology / genotoxicity'},
            {'detail': 'Nonclinical overview; orphan/rare pediatric disease designation; risk evaluation and '
                       'mitigation strategy (REMS) framework given the lentiviral malignancy signal.',
             'month_label': 'M8-M11',
             'sort_order': 4,
             'track': 'Regulatory package'},
            {'detail': 'Submit IND; respond to FDA queries (genotoxicity packages often draw additional '
                       'review questions - timeline risk of 1-2 months beyond the nominal 12-month program).',
             'month_label': 'M11-M13',
             'sort_order': 5,
             'track': 'IND submission'},
            {'detail': 'Site activation; first-patient dosing - realistically month 13-14 rather than month '
                       '12 given the added genotoxicity review common to this modality class.',
             'month_label': 'M13+',
             'sort_order': 6,
             'track': 'Clinical readiness'}]}

COST_ITEMS = {'atp6v0c': [],
 'drta': [{'high_usd_k': 500,
           'low_usd_k': 300,
           'name': 'Dose range-finding + 28-day GLP rat tox',
           'optional': False},
          {'high_usd_k': 900,
           'low_usd_k': 500,
           'name': '28-day GLP non-rodent tox (dog or NHP)',
           'optional': True},
          {'high_usd_k': 530,
           'low_usd_k': 270,
           'name': 'Safety pharmacology (CV, respiratory, CNS)',
           'optional': False},
          {'high_usd_k': 135, 'low_usd_k': 75, 'name': 'Genotoxicity battery', 'optional': False},
          {'high_usd_k': 320,
           'low_usd_k': 160,
           'name': 'Renal-targeted PK / ADME package',
           'optional': False},
          {'high_usd_k': 750,
           'low_usd_k': 450,
           'name': 'Reproductive & developmental toxicology (rat + rabbit)',
           'optional': True}],
 'tcirg1': []}

COST_SUMMARY = {'atp6v0c': {'allin_high_usd_k': 5000,
             'allin_low_usd_k': 2000,
             'note': 'CNS-delivered ASO (TANGO-style), intrathecal administration. Higher than a typical '
                     'N-of-1 ASO because CNS delivery, GLP neurotoxicology, and a for-a-defined-cohort (not '
                     'single-patient) regulatory package are assumed, following the zorevunersen/nusinersen '
                     'precedent class rather than the individualized-IND model.',
             'source': 'Directional estimate from ASO CNS program benchmarks (Nome.bio 2025 survey; general '
                       'antisense CNS program literature); not a single verified figure - recommend '
                       'CRO/platform-partner quotes.'},
 'drta': {'allin_high_usd_k': 5000,
          'allin_low_usd_k': 2500,
          'note': 'Small-molecule renal-targeted corrector, all-in candidate-selection-to-IND.',
          'source': '2025-2026 North American CRO benchmark compilations.'},
 'tcirg1': {'allin_high_usd_k': 10000,
            'allin_low_usd_k': 4000,
            'note': 'Ex vivo lentiviral HSC gene therapy: vector (lentiviral) GMP manufacture, CD34+ cell '
                    'processing/closed-system manufacturing development, conditioning-regimen nonclinical '
                    'package, and integration-site/genotoxicity analysis (large-animal or humanized-mouse '
                    'models) driven by the Skysona safety signal. No single verified consensus figure was '
                    'identified in this research pass; ex vivo lentiviral HSC programs are generally '
                    'considered among the most capital-intensive gene-therapy modalities because they '
                    'combine viral vector manufacturing with cell-processing and long-term genotoxicity '
                    'follow-up - this range is directional and should be confirmed with CDMO/CRO quotes.',
            'source': 'Qualitative synthesis from ex vivo HSC gene therapy manufacturing/preclinical '
                      'literature; no single hard consensus figure verified.'}}

CHECKLIST_DEFAULTS = [{'category': 'Pharmacology / proof of concept',
  'label': 'Target engagement / rescue assay in patient cells',
  'sort_order': 0},
 {'category': 'Pharmacology / proof of concept', 'label': 'Dose range-finding study', 'sort_order': 1},
 {'category': 'Toxicology', 'label': 'GLP repeat-dose tox, primary species', 'sort_order': 2},
 {'category': 'Toxicology', 'label': 'Safety pharmacology', 'sort_order': 3},
 {'category': 'Toxicology', 'label': 'Genotoxicity battery', 'sort_order': 4},
 {'category': 'Toxicology', 'label': 'Integration-site analysis (if lentiviral)', 'sort_order': 5},
 {'category': 'CMC', 'label': 'Drug substance / vector / cell product GMP manufacture', 'sort_order': 6},
 {'category': 'CMC', 'label': 'Analytical method validation', 'sort_order': 7},
 {'category': 'CMC', 'label': 'Stability program initiated', 'sort_order': 8},
 {'category': 'Regulatory strategy', 'label': 'Pre-IND / INTERACT meeting held', 'sort_order': 9},
 {'category': 'Regulatory strategy', 'label': 'Orphan drug designation filed', 'sort_order': 10},
 {'category': 'Regulatory strategy', 'label': 'Natural history study initiated', 'sort_order': 11}]

AGENT_DEFINITIONS = [{'description': 'Cross-checks top-3 gene UniProt accessions live against rest.uniprot.org',
  'name': 'genomics'},
 {'description': 'Live PubMed hit counts per top-3 gene via NCBI E-utilities', 'name': 'literature'},
 {'description': 'Live resolution metadata for the human V-ATPase cryo-EM structures via RCSB PDB',
  'name': 'structural'},
 {'description': 'Live Gene Ontology term definitions via EBI QuickGO', 'name': 'ontology'}]
